### ISSUE TITLE
odd, composite figures, Zoological Journal Linn. Soc.

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#10]
@gsautter this article has very odd figures which sometimes allow to be marked up as image, sometimes as graphics, and at the begin they often seem to be composites of many single images and lines and text.

http://tb.plazi.org/GgServer/summary/FF92FFD44F2AFFA9D41AFFF4FFAFFFC9

**Comment by gsautter** [comment]
True enough, I can see these figure problems right from the HTML summary ... that PDF is not even on Zenodo, and the DOI smashes me straight into a paywall, so little chances for me to get a look at it and see what you mean ...

From the top of my head, all I can say that what you observe is not at all unusual ... many of those multi-part figures are made up of individual images, with some thick-ish white lines acting as passe-par-touts, and letters marking the tiles. Those are combined into PNGs on upload to Zenodo.

Apart from that, dragging a box and using "Mark Image" should always do the trick ("More ...").

**Comment by myrmoteras** [comment]
I uploaded the IMF to TB and so you should have access to the source.pdf?!

**Comment by gsautter** [comment]
While it's loading, what I can say in general is that all those individual bitmaps and line drawings simply reflect what's in the source PDF ...

**Comment by gsautter** [comment]
And looking through this PDF, yes, those images come in very small bits.

On top of that, most of the line drawings are vectorized and render as PDF native graphics, which is why they come up a `graphics` rather than `image` regions. That doesn't mean they will extract any worse, though. If they don't contain any bitmap parts (like the phylogenetic tree on page 398, for instance), they go on Zenodo as SVGs rather than PNGs. Ones with bitmap parts (like Figure 9 on page 390), on the other hand, are combined into PNGs to accommodate the bitmaps.

There's nothing wrong with this one at all, it simply has a very different inner structure than the Zootaxa we're oh so used to.

It's only the figure-to-caption assignment that I'll have to investigate. Got a hunch it has something to do with captions being a lot wider than the figures they belong to ...
