### ISSUE TITLE
file does not open in GGI

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#103]
https://peerj.com/articles/3007.pdf

[GgImagine.20170301-1327.err.zip](https://github.com/gsautter/goldengate-imagine/files/810677/GgImagine.20170301-1327.err.zip)

**Comment by gsautter** [comment]
Another PostScript issue in a Type1 font ... you just seem to have an eighteenth sense for trouble PDFs ... and that's good, as no intentionally assembled test bed could potentially cover all the cases possible based on the PDF Spec.

Looks like something to take a stab at on the train on Friday ...

**Comment by gsautter** [comment]
Got it ... and solved. Was a problem with parsing the vector graphics descriptions of character glyphs, if one that only kicked in occasionally, and thus had gone undetected so far.

The fix comes with the next update, which will also include a fix for another problem I found in the same PDF: graphics are mis-placed under certain circumstances, which I think is due to a missing feature I did not have an example PDF to develop it on before you found this one here.

**Comment by gsautter** [comment]
The graphics are in place now as well, and this PDF opens just fine ... with enough RAM, that is, as the figures come in 900+ DPI (!!!), which gets a bit hard on memory.

**Comment by gsautter** [comment]
I put it on the server now, ID is FFABFFDB2067FFC1FF8BFFB77650E403

As the high-resolution figures only cause memory issues during decoding (and maybe while first uploading the document to the server, or first opening it from there), you should now be able to get it and do the markup.
