### ISSUE TITLE
can't get the doc from SRS FFB3FF9EB22DAC4A3022181FFFF8FFF0

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#110]
FFB3FF9EB22DAC4A3022181FFFF8FFF0
and I need to make sure the figures are linked

![image](https://cloud.githubusercontent.com/assets/4609956/23660438/ba3045d6-0349-11e7-8696-65c88bd8a22b.png)

**Comment by gsautter** [comment]
For some reason, it looks like Jeremy has been holding the lock on this one since September last year ... I've released it for you, hope not to destroy any good markup Jeremy might have added ...

Without the release, Zenodo upload just could not possibly kick in, as it needs the write lock to be able to store any newly created Zenodo DOIs in caption attributes.

I've triggered a run of Figure Repair now for good measures, and will trigger an upload to Zenodo if required afterwards.

**Comment by myrmoteras** [comment]
ok - this time it worked and is uploaded to TB http://tb.plazi.org/GgServer/summary/FFABFFDB2067FFC1FF8BFFB77650E403

**Comment by myrmoteras** [comment]
added to manual
https://docs.google.com/document/d/1mRSK4g0AVS1L4lbTYKH0Sq-7JRX5qEWfPsYGNcWJE6A/edit#heading=h.oirn4psd0m9b
