### ISSUE TITLE
brackets on authority

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#113]
from Markus: Btw, the extracted species name is missing authorship brackets. Is this sth you can improve? The article title has it right so it should probably be correct in the source.

B167FFE1FF901171FFDE1970704D076A

Do I just add them around the authority? 
![image](https://cloud.githubusercontent.com/assets/4609956/23704708/7a0e8216-0406-11e7-87b1-62710a20a7ef.png)

or how is this to be fixed?

**Comment by gsautter** [comment]
You can do that, sure, but it won't help all too much, since the authority is synthesized from the `authorityName` and `authorityYear` attributes whenever the latter two are present. That's the only way of reliably ensuring that both name and year are present, and either one or even both can well be taken from the treatment metadata for original descriptions.

If Markus generally wants those brackets added, we can easily do this, of course, if at the risk of _inserting_ brackets where authors originally didn't put any.

We can also export the verbatim taxon name string (in addition to all the details), which includes or doesn't include such brackets depending on nothing but the author's choice, but that would also mean retaining any abbreviations without resolving them, etc.

What information do these brackets convey, anyway? If there specific semantics to whether or not they are present, or is it author's choice and nothing but?

**Comment by gsautter** [comment]
On a related not: `authority` contains the verbatim authority as given in the document, which could be as little as "L.". The `authorityName` and `authorityYear` attributes, on the other hand, are meant for normalized values, e.g. "Linneaus" and "1758", respectively.

This normalization is important, especially for our LOD taxon concept URIs, as we sure as whatever don't want to implement nomenclature codes and taxonomists' common knowledge in the URL rewrite rules that help resolve those URIs. We normalize the data during markup, including making explicit what taxonomists implicitly know, so machines can handle it in a unified way ever after. The markup process is the one place to deal with all the oddities and special cases, not at last so not every system consuming the data afterwards has to implement all that special case handling.

**Comment by myrmoteras** [comment]
Brackets mean that the species has originally bee described in a different genus. This is a norm in zoology

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by gsautter** [comment]
Ah, OK, good to know ... or sorry for having forgotten ...

Question remains whether or not abstracting from this detail in favor of a massive reduction in technical complexity (both for the consumers of our data and fr ourselves) incurs any ambiguity, or even discards any actual facts ... I tend to doubt both, as there is always a link back to the treatment on TB, which faithfully preserves the original spelling. On top of that, wouldn't be a "comb. nov." invalid (or forbidden) if it incurred a homonym in the new genus? Wouldn't such a case require a (non-homonymous) "nom. nov."?

Anyway, it's only in our data centric exports that we make this abstraction at all, and the users of that data are most likely thankful for ease of processing rather than resentful about abstraction from taxon name syntax that expresses facts whose meaning most of them are likely happy about not even _having_ to understand.

We can of course make the DwC-As an exemption from this abstraction if required, as that export is Java based (not XSLT based as the LOD) and thus has the means at hand to preserve this kind of detail (would be a nightmare to implement in XSLT). Just say the word ...

And the ultimate question still is whether or not (in our data centric exports, and only in those, of course) we even _want_ to preserve such syntax details that may well convey some information, but then convey none we didn't have available in the form of the very treatment _making_ the recombination in the first place. When we abstract from treatments and move over to data, we also move from looking at individual treatments and what information can be derived from them over to looking at a massive body of treatments and what information can be derived from its entirety. And in the latter, ease of linking and stability of links is a lot more valuable than preserving syntactic complications conveying facts that at least as easily derive from the resulting graph. At least that's how I tend to see it.

**Comment by myrmoteras** [comment]
It’s Markus at GBIF who asks for this change, since brackets are part of a name, and in fact they have a real meaning. This system has always been in place and certainly is part of a concept name.

**Comment by gsautter** [comment]
Fair enough ... as stated in my previous comment, it's absolutely to preserve these brackets in the verbatim authority.

However, there is one question left: if the verbatim authority in the treatments is merely "(L.)", do you want that preserved as is as well, or should it be augmented to "(Linneaus, 1758)"? After all, those extremely concise abbreviations (or micro-citations, as Rich used to call them) have a tradition just as much as the brackets do.

**Comment by gsautter** [comment]
Just to complete the picture: We have established the semantic difference between "Nylander, 1856" and "(Nylander, 1856)". But what about "Nylander (1856)", or "Nylander 1856"? Is there any special meaning to those punctuation schemes as well? Only the year in brackets, or the comma present or omitted?

**Comment by myrmoteras** [comment]
As far as I know, only (Nylander, 1856) is relevant.  Other punctuation don't play a role, until we discover more or have deeper insights

**Comment by gsautter** [comment]
Taking another look at this one (see my mail earlier today), the one place where parentheses or not might play a role is in the `title` column of the `media.txt`, so I'm trying to change it there.

Hope Markus can shed more light so I don't have to take half a dozen stabs at where exactly to make the change.

**Comment by gsautter** [comment]
Authority Augmenter has been deployed for a while now and seems to work just fine.

The DwCA exporter is updated as well to comply with what we detailed out above.

The update of our entire collection has yet to happen, but implementation is done on this one.
