### ISSUE TITLE
candollea: figure and font issues

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#122]
[candollea.c2016v712a1.pdf](https://github.com/gsautter/goldengate-imagine/files/848060/candollea.c2016v712a1.pdf)

in this article, there is a font issue that I can't correct and unfortunately is part of the name of the genus Pentacðlaena should reach Pentachlaena

and the figures can't either be marked up at all 
![image](https://cloud.githubusercontent.com/assets/4609956/24002515/3fbe4d92-0a61-11e7-9658-72e2d96857aa.png)

or can not be marked up as one 
![image](https://cloud.githubusercontent.com/assets/4609956/24002555/5adafd6e-0a61-11e7-9f87-177653ba94d6.png)
this is from Candollea, a journal from Geneva, whose chief I will meet tomorrow

**Comment by gsautter** [comment]
The image marking issue should be fixed with the latest build.

**Comment by gsautter** [comment]
I cannot seem to reproduce the font issue, it comes up just as supposed to.

In such cases, you might want to try "&lt;Render Glyphs Only&gt;" or "Extended Latin" instead of "Default" for font decoding (it's faster as well ;-)
In fact, I tend to recommend using "&lt;Render Glyphs Only&gt;" by default, and only switching to something OCR based if the former brings up a scrambled document. Most PDFs use friendly fonts and faithful Unicode mapping, so any OCR based font decoding is little beyond wasted effort. It's just the oddjobs with the bad obfuscation and anti-text-extraction attitude that even necessitate the more advanced stuff. I know I did put a lot of effort in that latter stuff, but switching it off in the general case is a good idea (also in terms of performance), as all those font de-obfuscation techniques are mostly _aimed_ at the oddjobs we have seen over the past could of years.

**Comment by myrmoteras** [comment]
thanks, it is fixed and works
http://treatment.plazi.org/GgServer/summary/FFC2FFDCFFEBFC7E6667A77FFFA0033A
