### ISSUE TITLE
Bug: changes of entries in BLR metadata

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#130]
@gsautter when adding metadata to a deposit/article in BLR, the upload causes two proplems.

![image](https://cloud.githubusercontent.com/assets/4609956/24578636/8ea8dd16-16e4-11e7-92d2-f967e90003a4.png)
1. it overwrites entries that are already there. 
* The author names (see also below), 
* the date of publishing is changed (see also separate issue #131 )
* the affiliation is removed
* the keywords are changed
This should not happen and we have to fix it.

2. Author names are entered the wrong way. It should be Name, Vorname

**Comment by gsautter** [comment]
I guess this is a special case that only happens if a document is first put on Zenodo, and then run through GGI? The uploader writes the metadata it finds in the IMF, no matter what ... we need to implement a down-sync (import of PDF from Zenodo into our servers) to take over the metadata as it is, or create an import facility in GGI to fetch it based on the deposition ID, which is likely the easier way.

1.1 The year of publication is exactly what we specified it to be. Extracting the exact _date_ of publication is an open issue, I know. Hope to get around to implementing that soon.

1.2 We do not currently have any fields for affiliations in our GGI workflow, so those get overwritten, yes.

1.3 The keywords are generated by the uploader exactly the way we defined it. Again, the metadata gets overwritten.

2. The author names come as they are given in the document metadata, which you can edit on the IMF just the same.

**Comment by gsautter** [comment]
PS: I hardly think this is a GGI issue ... more likely a Zenodo synchronization one.

**Comment by gsautter** [comment]
A possible fix would be to have the uploader merge up the metadata it generates from the IMF with whatever metadata already exists on Zenodo. That would preserve attributes like the affiliation and key words. However, it would effectively disable removal of any erroneously added attribute, or at least necessitate coordinated removal on both systems, as synchronization would create the union of whatever is present in either system.

If we on top of that give precedence to the attribute values that already exist on Zenodo (which is perfectly possible), it would prevent any corrections made on the Plazi end of things to go through to Zenodo, effectively disabling TB side corrections.

This is a two-edged sword, as you might realize. Needs some consideration before moving forward. The ultimate question is what we consider the preferred in-route of documents, as well as of updates. If it is Zenodo, we might well give it precedence. If it is TB (search portal editing), however, we should likely leave it the way it is.
