### ISSUE TITLE
font issue: wrong glyph

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#142]
![image](https://cloud.githubusercontent.com/assets/4609956/24893923/fc62d196-1e86-11e7-9726-dd8c7e4b9403.png)

This glyph cannot be changed. with Edit Font, the wrong deteced glyph can be changed, but it does not change in the text, and is neither displayed as such.

I am using the latest online update of GGI

I also cannot upload the IMF file, which might be due to Internet line here in Lucca. So, here is the PDF 
[castanea_14-036r2.pdf](https://github.com/gsautter/goldengate-imagine/files/912166/castanea_14-036r2.pdf)

**Comment by gsautter** [comment]
This PDF loads perfectly fine with `&lt;Render Glyphs Only&gt;` ... that option should be your first choice whenever only a few of all the characters are mis-decoded.

Actually, `&lt;Render Glyphs Only&gt;` should be the default for born-digital PDFs, as the very most do provide faithful Unicode mappings for their fonts, and because it is _way_ less computational effort to use that even `Basic Latin` ... what do you think? At least for the UI, it would make tons of sense, I guess.

**Comment by gsautter** [comment]
On a font decoding note, I have to say that in this very font, the lower case `Y` is pretty special. However, if you even use `Extended Latin`, the decoder will get it right, as it won't even consider that exotic n-with-hook character.

**Comment by myrmoteras** [comment]
Let's try it out. I provide feedback as usual..

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
