### ISSUE TITLE
font: can't correct this font

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#149]
![image](https://cloud.githubusercontent.com/assets/4609956/26161319/e871348e-3b23-11e7-8437-790e97232934.png)
[De Chambrier etal_2017_Cichlidocestus.pdf](https://github.com/gsautter/goldengate-imagine/files/1008186/De.Chambrier.etal_2017_Cichlidocestus.pdf)

**Comment by gsautter** [comment]
The "R" is fine, I take it. The "I" and the "C" look like basic Latin characters with combining diacritic markers attached to them.

Could be the combinations don't have a PostScript name as a whole, at which point combining them fails. In this case they would be "Iacute" and "Ccaron", however, which are valid PostScript character names. There are other problems.

Another reason might well be the sequence of two such markers, with the first one following its associated letter and the second one preceding it, which is very inconsistent. Apart from that, a sequence of two letters with a combining diacritic marker each presumably is an _extremely_ rare case. However, there are yet other problems.

If you hover the few characters in questions in Acrobat with text selection active, you'll see the real problem: you'll see the the direction of your selector flip to horizontal, i.e., the text direction to vertical. Also, those diacritic markers are only very sloppily aligned with the letters they belong to, so the PDF decoder has a hard time figuring out that those guys actually belong together.
The real problem here is a pathologically rare sequence of letters in combination with sloppy copy editing.

As to correction, I suggest "Split Word" to get strip the letters from the diacritic markers, and then "Remove Word" or at least "Mark Artifact" to get rid of the markers altogether.

Correcting fonts only works for characters contained in fonts as a whole, not for ones made up from two without the two being really combinable. The acute accent and caron in this case are not even encoded as their combining variants (they both got two Unicode points, one for standalone occurrence and for combining left or, more rarely, right). Our PDF decoder recovers that where possible, but cannot do so in this case due to the sloppy alignment.
