### ISSUE TITLE
doi: omitting CrossRef DOI

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#154]
@gsautter in this case, the crossref DOI has been omitted. 
![image](https://cloud.githubusercontent.com/assets/4609956/26727673/eee0a6fc-47a7-11e7-92bd-882a03dea3b1.png)

we need to take care, that this is not happening. https://zenodo.org/record/583192#.WTFm4Z1960p

I added in this case a related identifier to the original doi

**Comment by gsautter** [comment]
Could you next time please include the Plazi document UUID? Saves me a lot of sifting around to find that guy ...

**Comment by gsautter** [comment]
This was due to an outdated style template, which expected a plain `http://...` DOI instead of the given `https://...` DOI. We fixed that for articles a good while ago, but this is a monograph, which has a different template, and thus must have slipped thus far.

I've updated the template now, will go to the server with the very next update.
