### ISSUE TITLE
broken file in SRS

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#166]
this file is completely misconverted

http://tb.plazi.org/GgServer/summary/FFB95E51494F5D59FFE30026FFFB0C48

**Comment by myrmoteras** [comment]
http://tb.plazi.org/GgServer/summary/FFABFFCF312AFF9AFFCAB132D536FFAF

![image](https://user-images.githubusercontent.com/4609956/28237551-63941522-6942-11e7-9b45-8c6d8b714a51.png)

**Comment by myrmoteras** [comment]
http://tb.plazi.org/GgServer/summary/C80DFF962100FFE4FF9FFB11FFA02B2A

**Comment by gsautter** [comment]
Wow ... there's something _really_ hinky with those three ... will check.

**Comment by gsautter** [comment]
In http://tb.plazi.org/GgServer/dioStats , it looks like those three documents don't even exist.

**Comment by gsautter** [comment]
FFB95E51494F5D59FFE30026FFFB0C48 got converted just fine, but is in a state like right after conversion, i.e., the batch didn't process it. Could be due to the error you reported in #165 .
Assuming that the other two suffered the same fate, I'll try and fix #165 first and then trigger batch runs on these three documents.

**Comment by gsautter** [comment]
These three are processing now, looks quite normal.
