### ISSUE TITLE
DOI not marked up / arcticle not processed in batch

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#168]
in this example, the DOIs are not marked up
![image](https://user-images.githubusercontent.com/4609956/28406758-10791466-6d32-11e7-9666-62d52a6e8b78.png)

![image](https://user-images.githubusercontent.com/4609956/28406850-5630bdce-6d32-11e7-9494-2f1b21efafa2.png)

[zootaxa.4294.2.8.pdf](https://github.com/gsautter/goldengate-imagine/files/1161570/zootaxa.4294.2.8.pdf)

this might be a queue why it did not work
![image](https://user-images.githubusercontent.com/4609956/28407013-e11cbaaa-6d32-11e7-86e4-408bc962b756.png)

I know uploaded the artilce to SRS zootaxa.4294.2.8 http://treatment.plazi.org/GgServer/summary/FF93FFC1FFA4EF5CFFDFFFEBF93D386F

**Comment by gsautter** [comment]
The DOIs might well be missed out on due to the "https://" protocol prefix, as the original tagger only observed "http://" ... fix comes with the next update.

As to the taxon name error: (a) please make that a separate ticket, as it's completely independent of the DOIs, and (b) please provide the logs (as for any red X error)

**Comment by myrmoteras** [comment]
How can I provide a log from batch processed files, if there are twenty files in queue?

**Comment by gsautter** [comment]
There should be a log file named `GgImagineBatch.<startDateAndTime>.log` ... that will always be enough for me to search for the error message.

And still, the error message doesn't have anything to do with the subject of this ticket.
