### ISSUE TITLE
treatment not found: table error

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#170]
because the table has been too much extended, the treatment has not been found

![image](https://user-images.githubusercontent.com/4609956/28408493-f7dfd1d2-6d37-11e7-956f-261411d82cef.png)

**Comment by gsautter** [comment]
OK, I see the problem ... won't happen with the new table handler (which I hope to get around to finishing soon), as the latter will use the black lines for orientation.

Closing this issue because the solution has long been conceived and designed, and implementation is well underway / close to finishing. Actually, it was error like this one that got me started building the new table extractor.
