### ISSUE TITLE
materials_citation does not work

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#173]
![image](https://user-images.githubusercontent.com/4609956/28409876-3ea5a426-6d3c-11e7-896a-6cbe8763843a.png)

zootaxa.4294.1.12

**Comment by gsautter** [comment]
Same as with the error you mention in #168 ... log file please.

**Comment by gsautter** [comment]
I got a similar exception running zootaxa.4294.3.2 (from #174) through the batch while testing the #174 exception fix. Was an exception happening in an edge case of the code that detects non-catalog collection codes based on surrounding punctuation.

Most likely fixed this one afterwards. "most likely" because I could only test with zootaxa.4294.3.2, but not with the one mentioned above.

**Comment by myrmoteras** [comment]
I am running the files again – let you know asap
