### ISSUE TITLE
unusual slow processing zootaxa.4306.2.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#198]
[zootaxa.4306.2.1.pdf](https://github.com/gsautter/goldengate-imagine/files/1227126/zootaxa.4306.2.1.pdf)

This file is unusually slowly processing

**Comment by gsautter** [comment]
Looks like some font might be the culprit here ... if fonts come without a usable Unicode mapping, the PDF decoder has to figure out the characters by itself, which is indeed some effort.

Zootaxa thus far mostly provided fonts with a good Unicode mapping, but this one isn't the first that deviates from this line. Just need to let the decoder do its work, I'm afraid ...

**Comment by myrmoteras** [comment]
ok - it worked now and is uploaded

**Comment by gsautter** [comment]
OK then ... if fonts become an issue with Zootaxa more frequently, we might have to either talk to them, or just live with it until they come talking to us ...
