### ISSUE TITLE
table issue

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#204]
![image](https://user-images.githubusercontent.com/4609956/29617985-f1d81ce6-8816-11e7-9a6b-6cce6f0449ae.png)

this is a table of characters that is not properly resolved, in some cases not even discovered.

![image](https://user-images.githubusercontent.com/4609956/29618056-271b8564-8817-11e7-899b-dd62051f2109.png)

file B355

**Comment by gsautter** [comment]
OK, this is an all new challenge ... monospace fonts (usually used in programming environments like Eclipse to better visualize column alignment, and previously in DOS because fixed-width characters render more easily) in something like a table denoting (I assume) some kind of gene sequence.

Thus far, the PDF decoder is only tuned to (and only ever has encountered) variable-width fonts (that replaced monospace fonts in the mid-90s as a visual revolution), which are what publications are usually rendered in. This is just a whole new aspect of font decoding that I'll have to extend the PDF decoder to handle ...

Could you please provide the source PDF as a download, either here or on our Google Drive, so I have something to test with?

**Comment by myrmoteras** [comment]
this is in fact the normal case in phylogenetic publications and publications that provide alignement of DNA sequences.

the link is here - the file is too big to add 56MB and sorry that I didn't add the link: 
https://hdl.handle.net/2246/6124

there is also the imf B355.pdf.imf

**Comment by gsautter** [comment]
I wasn't aware we're diversifying into phylogeny now ... but OK, it's an interesting test case that the PDF decoder should be able to handle.

I'll try and have a look tomorrow on the train. Font issues have become my favorite on-train tasks, as they require little to no web connectivity.

**Comment by gsautter** [comment]
One week and another train ride later, I finally figured out the monospaced font, as well as word width scaling in general:
![image](https://user-images.githubusercontent.com/5789714/30220861-6b8598fa-94c1-11e7-8299-c1d9a3a91cae.png)

I'll have to implement the improvements through to (a) other font directions, (b) page image updates after font corrections, and (c) rendering of image labels, though.

Comes with the next build, hopefully this weekend.

**Comment by myrmoteras** [comment]
Cool! Of to phylogénies...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gsautter** [comment]
Implemented through to all relevant word rendering code.

Build to come.
