### ISSUE TITLE
document metadata wrong

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#207]
in this case, I added a wrong name for Roberto, Robert that is. I fixed this manually in the article in Zenodo, but there are 30+ images that need be fixed. 
I opened the doc again in GGI and changed the doc metadata. Will this be changed now for all the images?

https://zenodo.org/record/847641#.WZ3kVFJL_AQ

**Comment by gsautter** [comment]
I'm afraid you'll have to somehow store the correction ...

Our Zenodo synchronization usually _will_ update the metadata if it changes, but that change has to be stored on the server. If the latter did happen, but the former did not, I'll have to check ... could be I have to manually re-trigger the update to Zenodo because something went wrong on the one triggered by the original metadata update of yours.

**Comment by gsautter** [comment]
Looks OK now.
