### ISSUE TITLE
new journal: Quarterly review of biology; table, font, page layout, break up issues

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#211]
this is an interesting journal with some issues of general interests

font: font's cannot be edited
![image](https://user-images.githubusercontent.com/4609956/29740037-cbda631c-8a4d-11e7-8c10-9c82e561f654.png)
![image](https://user-images.githubusercontent.com/4609956/29740052-fa711cc0-8a4d-11e7-9fe9-63ce57de8206.png)

Tables not detected

Mixed pages with one and two columns

many appendices with many references: candidates to take them out as separate documents for BLR?

**Comment by gsautter** [comment]
PDF please, or at least a BLR ink or IMF UUID ... at least if you want me to pursue this issue ...

**Comment by gsautter** [comment]
The fonts are _really_ strange in this one ... the editor opens, and as you see the characters are transcribed just fine.

![image](https://user-images.githubusercontent.com/5789714/29742619-f187a806-8a82-11e7-939d-032dc9807429.png)

It's only that the character code sequence attributes of the words (`fontCharCodes`) are mingled in some way. For instance, "BIOLOGY" in the title has char code sequence `0F100203021112`, but based on the font (see above) should have `42696F6C6F6779` ... will have to check what goes wrong in decoding.

**Comment by gsautter** [comment]
The jump from a one-column abstract to the two-column main text on page 2 is not all too much of a problem, not even for a potential document style template.

**Comment by gsautter** [comment]
Table 1 detects just fine.
Table 2 at least correctly splits into rows and columns after manually dragging the correct bounding box around it. The new table detector will do just that automatically based on the table's bounding lines.
Tables 3 and 4 look OK as well.

**Comment by gsautter** [comment]
The page bottom watermarks ("This content downloaded from 216.073.244.041 ...") will be easily removes with a style template, with the help of the page content box setting, which specifies the area of the page that contains the useful content (the rest is page margin).

**Comment by gsautter** [comment]
I might also add a respective function (maybe "Restrict Page Content") to the context menu to clean up the page margin in one go. Making sense?

**Comment by gsautter** [comment]
The appendices might indeed pass as articles in their own right, and maybe in other journals would be.

Maybe we introduce marking some sort of `subDocument`s in such cases, and extend the Zenodo uploader to observe them if they exist.

On the other hand, it's still all the same article, and we could just aggregate and keep together all the references, both from the article proper and from the appendices. After all, all the latter have the same bibliographic data, so they are one and the same citing instance from the bibliometric point of view. What real difference would it make if we upload the appendices as separate depositions?

**Comment by gsautter** [comment]
As to the `fontCharCodes` attribute of the words, which facilitates correcting fonts, I do get the expected result, and fonts are correctable.
The reason for you getting a different result might well be an outdated decoder version, which might still be on your laptop (you mention working on that machine in #213).

As to the fonts proper, I still do get the same, but that's a different problem altogether ... the characters in question in fact do Unicode-map to lower case (you can see that by copy&pasting the fist page of the PDF to a text editor). It's just in the case of these few characters that the font decoder cannot tell that the glyphs are in lower case because they scale up to their upper case counterparts. For all the other glyphs, correction kicks in.
We have a similar problem the other way around with small-caps, and have resolved it a good while ago. It's just that this direction of error is way rarer, and thus the decoder doesn't yet check it. I'll see what I can do.

**Comment by gsautter** [comment]
An example of how our own well read pairs of human eyeballs handle small-caps:
![image](https://user-images.githubusercontent.com/5789714/29840268-b56fbf44-8d01-11e7-9577-1b1996775be9.png)
If you look at each of the two words individually, it's clear the first is normal, and the second is small-caps. Yet, all they ever differ in is the "n" or "N", the rest is identical to the pixel. Amazing what our brain does, isn't it?

**Comment by gsautter** [comment]
Above a visual example intended to tell you what kind of task the font decoder is faced with when dealing with small-caps ...

Was able to solve it now, though, based on the same character (glyph) neighborhood analysis that also helps us with glyph decoding when there is no Unicode mapping, or when the latter is abused for obfuscation. To come with the next build.
