### ISSUE TITLE
materials citation processing , UUID 735C952FFFCAB1543860CC2CB35C6E75. 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#215]
, UUID 735C952FFFCAB1543860CC2CB35C6E75. Bull Am. Mus. Nat. Hist., which is uploaed to TB an processed to TreatmentStructure.

I am not sure, whether the processing of the materials citation is working or not - it does something now for an hour. I am letting it run. When do I know, that I have to kill a process? Which does it only use about 16% of the CPU?

![image](https://user-images.githubusercontent.com/4609956/29749364-ce390fe6-8b29-11e7-9ab6-e3bbe6ba2c29.png)

![image](https://user-images.githubusercontent.com/4609956/29749368-e20f0282-8b29-11e7-879e-6d570c53e7a3.png)

**Comment by myrmoteras** [comment]
ok - I killed it

[GgImagine.20170827-1028.err.zip](https://github.com/gsautter/goldengate-imagine/files/1254361/GgImagine.20170827-1028.err.zip)

This is probably as good as it gets in terms of materialsCitation - and it seems to be a challenge for you.

let me know, what I can do to make this fly.

**Comment by gsautter** [comment]
Got it ... in this case, parsing the details goes south due to a failure to properly separate a sequence of materials citations, which results in several actual materials citations to be investigated for details as a single materials citation, ultimately containing so many details that parsing has all too many options to cover.
The culprit (on page 86) is "MATERIAL EXAMINED: BRAZIL: Bahia: Barra, Igarite, 5. vi. 2008, 1 ? (MZSP 31122 / AMCC [LP 9963]); Catu, Ibiraba, 2. viii. 2000, 1 ? (MZSP 31123 / AMCC [LP 9953]); Guanambi, Ceraima, 14 ° 13 ' S 42 ° 46 ' W, 10 - 17. xii. 2007, H. Y. Yamaguti et al., 1 ? (MZSP 30881 / AMCC [LP 9684]); Guanambi, 7 km S, 14 ° 17 ' 5.6 ? S 42 ° 47 ' 2.2 ? W, 533 m, 24. i. 2007, C. I. Mattoni, R. Pinto-da-Rocha, and H. Y. Yamaguti, UV sampling, modified savannah, cloudy and raining, 1 juv. (AMCC [LP 7638]); Guanambi, 16 km SE, 14 ° 17 ' 19 ? S 42 ° 41 ' 31.1 ? W, 559 m, 25. i. 2007, C. I. Mattoni, R. Pinto-da- Rocha, and H. Y. Yamaguti, UV sampling and under leaf litter, banana plantation and surrounds, 1 juv. (AMCC [LP 7655]); Fazenda do Fabiano, 8 km NE Guanambi, 14 ° 10 ' 17.6 ? S 42 ° 43 ' 56.4 ? W, 539 m, 24. i. 2007, C. I. Mattoni, R. Pinto-da-Rocha, and H. Y. Yamaguti, under rocks, rocky hill and surrounds, open savannah modified, 1 ? (AMNH), 1 ?, 2 juv. (AMCC [LP 7639]); ...", which fails to split due to the square brackets around the specimen codes, e.g. in `AMCC [LP 7639]`. I'll add this option and try again.

**Comment by gsautter** [comment]
I finally got this to run smoothly ... both adding the double bracket option, and afterwards quite a bit of fiddling around with how our materials citation handler figures out where individual materials citations start and end. Comes with the next build.

Please keep on reporting such problems, as given the variability of materials citations, it is essential to get as many and as diverse test cases as possible to improve over time. I always knew this would be an iterative process, as it is virtually impossible to foresee, consider, and handle all the possible cases right from the start.
