### ISSUE TITLE
GGI name markup does not work

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#22]
@gsautter in this article, names are not being marked up. it is the same ms that had the problem with the strange h

IMF is uploaded to TB 

[errorLog20161209_gsautter the new built of GGI does not markup names.pdf](https://github.com/gsautter/goldengate-imagine/files/642160/errorLog20161209_gsautter.the.new.built.of.GGI.does.not.markup.names.pdf)
as AM52_38_49.pdf

**Comment by gsautter** [comment]
Will check ... 

However, that "strange H thing" is not really a thing, beyond a mis-decoded glyph, which can well happen every now and then with artsy italics fonts. See my last comment in #20 : there are _two_ _different_ spellings in the very document (just take a close look at the original PDF), so fixing one single character will definitely not make them the same.

**Comment by gsautter** [comment]
After correcting the fonts and marking bibliography and respective citations, I ran FAT, and it came back with an almost perfect result. Only error was author "Tobias Bauer" mistaken for a genus with authority "Bauer", but that is due to "Tobias" actually being a valid genus epithet, and one from the very same spider family ("Thomisidae") the document is about ... pathological case, that, the really odd kind ... see http://www.catalogueoflife.org/col/webservice?response=full&name=Tobias

**Comment by myrmoteras** [comment]
wo ist da doc jetzt? auf TB ist nichts markiert.

**Comment by gsautter** [comment]
I didn't upload it ... yet ... thought you were running it ...

But OK, I try to upload it - only to get a "Checked out by other user" ... guess you're still holding that lock, so I have no chance to upload my version.

Mine is marked to the taxon names, bibliography parsed, citations tagged, metadata added, and all fonts corrected.

**Comment by myrmoteras** [comment]
ok - hab den rest noch gemacht und lad es jetzt hoch
Ist ein wirres Ding - jetzt, nachdem ich es wieder runtergeladen habe, konnte ich die Namen markieren.

**Comment by gsautter** [comment]
Restart / reload tends to help a lot in cases where something suddenly hangs that normally works ... could have gone something wrong with the in-memory representation, for instance, that is just resolved when you save, close, and reload from disk, as then the in-memory data structured are reset.
