### ISSUE TITLE
Font issue: no letters at all FFDBFFC4461B2E06DC3E635F7120FE01 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#276]
all the letters of this title do not convert properly

![image](https://user-images.githubusercontent.com/4609956/31124566-aead606e-a84d-11e7-81cc-2668f0eb700e.png)

**Comment by gsautter** [comment]
Looks weird indeed ... the "Copy & Paste from Acrobat" test indicates the font in this sub title is pretty unfriendly. Will test.

**Comment by gsautter** [comment]
However, using "Latin" for the font decoding instead of "Render Glyphs Only" swiftly does the trick:
![image](https://user-images.githubusercontent.com/5789714/31138282-35b74960-a86e-11e7-8520-115c284dbbb5.png)

In general, while I keep recommending "Render Glyphs Only" as the option to start out with, the first thing to do in case of misfigured or garbled fonts is re-decode the PDF using "Latin" or "Latin Full", and clear out the page image cache in between.

**Comment by gsautter** [comment]
PS: That screenshot is not from GGI, but from my test tool. Uses the same decoding facilities as GGI, but comes without a UI and with a good few debug switches that help me investigate problems.
