### ISSUE TITLE
large file cannot be opened

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#28]
@gsautter this file has been converted (540 pages with many names, but now I can't open it again.

I am uploading the IMF to GG: once done I add the link here https://drive.google.com/file/d/0B_yrQwn4yBySaEhOYnk2WWhLRm8/view?usp=sharing 

![image](https://cloud.githubusercontent.com/assets/4609956/21227275/7890f3b0-c2d9-11e6-92f1-248630ae6fba.png)

Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.
Exception in thread "LoaderThread" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.substring(Unknown Source)
	at java.lang.String.subSequence(Unknown Source)
	at java.util.regex.Pattern.split(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at de.uka.ipd.idaho.im.util.ImDocumentIO.setAttributes(ImDocumentIO.java:1471)
	at de.uka.ipd.idaho.im.util.ImDocumentIO.loadDocument(ImDocumentIO.java:598)
	at de.uka.ipd.idaho.im.util.ImDocumentIO.loadDocument(ImDocumentIO.java:342)
	at de.uka.ipd.idaho.im.imagine.application.GoldenGateImagineUI$45.run(GoldenGateImagineUI.java:1692)

.....................
source.pdf
Reading document data
Reading font data
Adding font T4
Adding font T6
Adding font T7
Adding font T8
Adding font Times-Bold
Adding font Times-BoldItalic
Adding font Times-Italic
Adding font Times-Roman
Reading page image data
Reading page data
Adding 548 pages
Reading word data
Adding 445887 words
Auto-Closing InputStream for 'Plugins/ImsDocumentIOData/cache/663432361/D720FFDA046FFFFDFFF5B267FFDCFF98/source.D720FFDA046FFFFDFFF5B267FFDCFF98.pdf'
Chaining text streams

**Comment by gsautter** [comment]
Was that document converted via batch processing, or in GGI proper? In the latter case, especially for documents this size, it's always a good idea to store as "Image Markup Directory", which is a lot easier on resources on re-opening.

**Comment by myrmoteras** [comment]
has been part of the batch - how to proceed?

**Comment by gsautter** [comment]
Do you have a `<GGI>/DocumentData` folder? If so, what's in there?

Also, are you attempting to open the document from the server, or from your local machine? In the latter case, closing and re-opening GGI might do the trick, as the report about `Plugins/ImsDocumentIOData/cache/663432361/D720FFDA046FFFFDFFF5B267FFDCFF98/source.D720FFDA046FFFFDFFF5B267FFDCFF98.pdf` up in the log tells me there is also some server related stuff going on, which of course also takes up resources. In general, with memory issues, the first thing to try is giving GGI a fresh start and trying one document at a time.

**Comment by myrmoteras** [comment]
I cannot upload the file to the server. It is still local.
Closing reopen doesn't help.

![image](https://cloud.githubusercontent.com/assets/4609956/21229097/b0e7822c-c2e0-11e6-9753-d84b7247fa63.png)

here is what's in the zt02455...
![image](https://cloud.githubusercontent.com/assets/4609956/21229182/fe92e232-c2e0-11e6-9aa7-7360648581d0.png)

**Comment by myrmoteras** [comment]
it always stops at this point
![image](https://cloud.githubusercontent.com/assets/4609956/21229226/21b0ef34-c2e1-11e6-8c2c-5615d38f01d4.png)

**Comment by gsautter** [comment]
OK, looks like the un-zipping the IMF to a folder part does work (that's what `<GGI>/DocumentData` is good for, namely to give you the resource savings of the directory storage mode).

Could be your GGI installation is restricted to 1024MB of RAM, though, judging from the Task Manager screenshot above. Have you tried and used "Configure" button in the "Select Configuration" dialog to increase memory? Maximum RAM does get reset with every build you freshly download, if not with a plain configuration update or with the dedicated online updates. That's simply because a whole build is a fully blown fresh installation that has no way of knowing if there was a previous installation on your machine, and no right to inquire about the same.

Using the registry on Windows and dedicated config storage locations on Linux could overcome the above with some effort, but then storing parameters in those locations also requires system privileges that many users don't necessarily have, rendering installation a lot more complicated than the current "Download, Un-Zip, and Run" (I've come to call it "Dump & Run") approach, which is something we don't really want, do we?

**Comment by myrmoteras** [comment]
now, I can open it . But the treatments are wrong. What is the best way to fix these 500 odd pages?

**Comment by gsautter** [comment]
What exactly is wrong about the treatments? Numbered ones not observed? In that case, the current version of "Mark Treatments (Headings Only)" should do the trick.
