### ISSUE TITLE
table broken : zootaxa.4290.1.3  94066857FF81FF869814FFFAFFBDFF9D

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#281]
here is a broken table. I marked it as table,
![image](https://user-images.githubusercontent.com/4609956/31543371-091155c2-b016-11e7-9b37-f31c3de45563.png)

![image](https://user-images.githubusercontent.com/4609956/31543400-2305e4ac-b016-11e7-9c3a-ae867ed9aca7.png)

**Comment by gsautter** [comment]
Looks more like a font problem to me ... i.e., the table fails to be detected because its content is broken. Will investigate.

**Comment by gsautter** [comment]
Turns out this is indeed a font issue ... one of the cases where "Render Glyphs Only" just doesn't do the trick. Thinking about an auto-detect mechanism so the PDF decoder can adapt ...

Auto-detection or not, whenever you encounter something like this after decoding with "Render Glyphs Only", try re-decoding with the "Latin" option - it usually does the trick, as it did for me in this case (for both pages).
