### ISSUE TITLE
images don't show up

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#29]
http://tb.plazi.org/GgServer/html/CE438843FFBD8800AE241BA4FAE0B024

**Comment by gsautter** [comment]
Yes, and my browser says "Waiting for zenodo.org" when I hit "View Figure" ... hard to tell what's going on there, but it's beyond my reach to find out. Happy to diagnose problems on a third party system nonetheless.

This treatment is actually four conflated in one, by the way, with paragraphs badly mingled in the second and fourth. I'll take care of that.

**Comment by gsautter** [comment]
Seeing some server side errors on Zenodod uploads in the server console right now, so it seems there is a problem on their end. Just hope we didn't break their system yet again ...

**Comment by myrmoteras** [comment]
Did you send them an email?

**Comment by gsautter** [comment]
Not yet ... it worked just fine all day until a little while ago. If the problem is still there in an hour or so, I'll drop them a mail. Until then, it's most likely this is a temporary issue cause by god knows what, and odds are it will disappear as suddenly as it emerged. No use bugging server admins with short-lived issues that will likely disappear before any chance of investigation. And if there is a real issue, maybe caused by an update, they are most likely up to it and have better things to do than answering mails reporting something they are already working on. Just keeps them from working the actual problem.
