### ISSUE TITLE
bbiRef: not all detected FFFDFFA5FFBEFFC88947DE39FF81F161

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#326]
![image](https://user-images.githubusercontent.com/4609956/32265373-0a6f6432-bee3-11e7-888f-163c66311288.png)

**Comment by gsautter** [comment]
Looks like a bad case of "van" getting in the way. If it was only one or two references, they would be "bridged", i.e., inferred to be references from the fact that they are surrounded by references. But that doesn't work with five successive references, as bridging such a high number of paragraphs would do more harm than good in the general case.

However, I'll most likely replace the reference tagger altogether as part of the RefParse makeover, using the latter's far more flexible author list tagging mechanism instead of those ten year old patterns we currently still have in use.
