### ISSUE TITLE
Implicit citation: how to add a httpURI to link from text to a figure in the text?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#36]
@gsautter in the Flora of Switzerland, the figures have not figureCitation nor do they have a caption. 

http://treatment.plazi.org/id/A71D664D-3E3B-ACBC-9E52-7304B6FFCEBB

How can I link them, once they are on BLR? If I add them as httpUri to the taxonomicName element, they are cited a treatment.

**Comment by gsautter** [comment]
Adding an HTTP URI for a figure to a `taxonomicName` won't help here, as upload to Zenodo works exclusively via `caption` annotations.

You could annotate a `caption` in the flowing text and assign it to the figure, however.

**Comment by myrmoteras** [comment]
As mentioned, this Flora der Schweiz I decided to use to run via GG piB, based on a html. The editing of the the Flora Europeana in GGI is very difficult, also because the image to work with is not really helpful. The letters are not clear, and often the word boxes are slightly shifted.
And I needed to get the Flora of Switzerland into the system, which I have done now.

The drawback are the images. Which take a lot of time to enter and link with the document.
Still, it is not clear how best to add them to this document.

Another are some more advanced tools in GGI – but they could be probably also implemented in GGpiB

Another issue is that I wanted to get the illustrations at 600dpi which is not possible from the 400dpi scan.

We need to go through the processing of these sannced floras to find an optimal way in the future, especially if we are looking for dealing with thousands of pages

**Comment by gsautter** [comment]
Well, scan quality is an issue, yes. If scans are too faint, and then binarized, there is no way back to more complete figures, especially with line drawings, where lines may fall below binarization threshold and partially disappear as a consequence. Maybe we should use grayscale, as binarization is straightforward, while the way back is now.

The word bounding boxes are indeed a bit of a problem, both ways: Using Tesseract, they end up tightly around the words, which renders them quite unregular vertically (consider the bounding box of a plain dash against the one of a wor with capital letters and descending letters ...). Using embedded OCR, on the other hand, the bounding boxes tend to be more regular (ABBYY seems to adjust them to the lines), but that incurs problems with the OCR overlay, as the latter is currently implemented to work with the tight bounding boxed produced by Tesseract. I've been trying to figure out a solution since Monday ...

Caption-less figures, in turn, are not _strictly_ an issue related to scanned documents, are they? True, they might occur more frequently in older documents, which naturally come as scans, but can happen in contemporary born-digital documents as well.
Anyway, we'll figure out a way of linking them to the main text ... even those figures have to be referenced in some kind of way, I guess? Or at least they have to be obviously associated with some text passage, so a user can make the connection. If we annotate the latter, we'll have a place to put the HTTP URI.

**Comment by myrmoteras** [comment]
just to make sure (and you don't spend more time on this right now: This is all done for the Flora of Switzerland right now, including the images linked to the first word in the description
http://treatment.plazi.org/id/A71D664D-3E3B-ACBC-9E52-7304B6FFCEBB

**Comment by gsautter** [comment]
That's about what I meant bringing up in-text (pseudo) captions ... little else we _could_ possibly do in this case anyway.

It's just that _assigning_ the figure to the in-text pseudo caption should be easier in GGI, and with the assignment in place, the whole downstream handling works automatically, including upload to Zenodo. The Zenodo upload does not at all care whether a `caption` annotation is a text stream of its own (the usual case), or whether it's embedded in a larger piece of (main) text - all it does is take `caption` annotations, determine the target figure (be it a single figure image, a scan cut-out, or a multi-part figure), put the figure on Zenodo, and attach the resulting HTTP URI to the `caption`. Consequentially, that mechansim should seamlessly work with in-text pseudo captions.
