### ISSUE TITLE
bibRef author not complete

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#365]
![image](https://user-images.githubusercontent.com/4609956/32950651-65adac0c-cba7-11e7-8d12-b72d6de11225.png)

**Comment by gsautter** [comment]
Yet another instance of the problems RefParse currently has with author lists in general and initials in particular ... the main reason for the makeover currently in progress.

I'm closing this one as a duplicate because (a) the RefParse makeover will definitely resolve it and (b) we have so many similar test examples already.
