### ISSUE TITLE
name detetion

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#37]
@gsautter this is a simple article with >100 names which causes problems.

https://doi.org/10.5281/zenodo.218051

[Tohme_Tohme_2014_LSJ_AntsLebanon.pdf](https://github.com/gsautter/goldengate-imagine/files/668468/Tohme_Tohme_2014_LSJ_AntsLebanon.pdf)

**Comment by gsautter** [comment]
The first thing that jumps my eye in this one is the title ... "Hymenoptera: Formicoidae" instead of "Formicidae" (mind the second O), which results in an empty catalog lookup results for the family. That in turn foils the "family present in document" vetting for genera.

What does work is vetting via labeled epithets (subspecies and varieties), but that will only save the day for the genera that have such a sub-specific name present in the document.

Would it be correct to establish a rule that if some "-oidae" name is present in the document, we can also consider the respective "-idae" name present? That would surely save the day in this one, but before I introduce such heuristics, I need to know for sure whether or not it could also incur errors ... so, what is the "-oidae" vs. "-idae" difference all about?

**Comment by myrmoteras** [comment]
Formicoidea (sic) is the superfamily
-idae the family

Yes. if a -oidea is present, then you can infer a -idae in animals

**Comment by gsautter** [comment]
OK, I'll adjust the catalog lookups accordingly.

Question remains why authors give the super family instead of the (for what I've seen more usual) family in the article title ...

**Comment by gsautter** [comment]
OK, let the authors have their way ... FAT does handle it now, and has been for a good while.
