### ISSUE TITLE
missing figures in TB

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#39]
@gsautter 
might it be possible to check this treatment why the images do not show up? The Figs/FigCit seem to be marked up
http://tb.plazi.org/GgServer/html/0328B127FFBDE61B131763746D8AE999

**Comment by gsautter** [comment]
Looks like this was just a little delay in upload ...

I triggered it manually via the console, and it was finished a minute later (so problem solved now).

Afterwards, I checked which versions of the document existed, and there was another one originating from the Zenodo uploader created a minute before I triggered the update.

Please not that due to figure repair (which should be done soon, however), Zenodo upload can take some 15 minutes or so. That happens if your _release_ of the document in GGI coincides with figure repair just having triggered an upload of a large document, as then your document gets queued up behind the currently uploading one.

**Comment by myrmoteras** [comment]
but this one has been uploaded yestereday. so it is was not just 15 minutes in this case.
thanks for fixing it

**Comment by gsautter** [comment]
Uploaded / updated maybe, but not released for what I see in the logs ... Zenodo upload can only kick in after you release the document (close it in GGI via "File -> Close Document"), as it needs to acquire the lock to be able to write back any newly added HTTP URIs.
