### ISSUE TITLE
table structure 8F496D43FFBAFF8B3360EC6F6A3DFFF7

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#395]
![image](https://user-images.githubusercontent.com/4609956/34295430-b0873316-e70d-11e7-8bb5-108ada56f619.png)

I can't fix this one, so it might be new?

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/34295473-dd6045e4-e70d-11e7-8c83-63894fbac5d3.png)

**Comment by gsautter** [comment]
Are you sure this is the right UUID? Table 5 from the UUID in the title looks like this:
![image](https://user-images.githubusercontent.com/5789714/34300283-9894cef2-e727-11e7-80f4-16b70a16229c.png)

**Comment by myrmoteras** [comment]
you are right - it is this F2377C2EFFEEFFC527125B50FFE8FF9B

which is also issue #396

**Comment by gsautter** [comment]
I was able to fix all the tables through Page 16 without problems. Some were a bit inconsistent, most likely because "Detect Document Structure" still uses older code to mark tables.

What helps the very best in such cases is to simply remove the table ("Remove table region", the rest is cleaned up automatically) and then use "Mark Table" for a completely fresh start.

**Comment by gsautter** [comment]
Closing this one, continuing in #396
