### ISSUE TITLE
swiss species 2016: article does not decode

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#41]
This is part of the LOD species decribed in 2016 by swiss scientists

@gsautter this artile does not decode at all. just run it in GGI and halfways throught the process is killed
[Ghielmi_et_al-2016-Journal_of_Zoological_Systematics_and_Evolutionary_Research.pdf](https://github.com/gsautter/goldengate-imagine/files/696897/Ghielmi_et_al-2016-Journal_of_Zoological_Systematics_and_Evolutionary_Research.pdf)

**Comment by gsautter** [comment]
This one decodes just fine with my latest code ... however, I can imagine it doesn't with your current build just yet, most likely due to the table on page 6 written bottom-up.

There was a problem with flipping the graphics elements of such tables to the horizontal, which I identified and solved yesterday with some other PDF. That fix is not out just yet, will be available within the next couple of days.

For now, you can download the IMF from http://plazi2.cs.umb.edu/GgServer/Ghielmi_et_al-2016-Journal_of_Zoological_Systematics_and_Evolutionary_Research.pdf.imf (it's too large to send by mail at 26MB, and GitHub doesn't like IMF ...)
