### ISSUE TITLE
treatment: Treatment not discovered zootaxa.4375.3.2

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#414]
recently, zootaxa showed up where the treatments have not been discovered.

![image](https://user-images.githubusercontent.com/4609956/35376450-8170fb44-01ab-11e8-89c6-c0b59d47feb5.png)

9D7F7D16FF9CFF89FFADFFB1FFCEA460

**Comment by gsautter** [comment]
As the taxonomic names apparently do detect as supposed to, this must be about the headings ... will check.
Inevitable, my very first take on this is a styling anomaly, most likely a deviation in the font size department.  Aka another instance of sloppy copy editing ...

**Comment by gsautter** [comment]
Turns out my first take was wrong ... this one is a side affect of a change to the treatment tagging rules that we introduced in the course of the EJT effort: "Results" starts a `subSections` of that very type, and straightaway includes the paragraph immediately following the respective heading. Which in this case takes us right past the treatment heading ... I'll think up a way of modifying the rules to prevent such misses.

**Comment by gsautter** [comment]
Figured it out ... simply increased the precedence of headings that start with taxon names over the "continue after controlled vocabulary heading" rule.

Let's hope this doesn't incur any unwanted effects ... but most likely only time and the constant influx of new documents with new peculiarities can tell.
