### ISSUE TITLE
wrong bibRef parsing

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#42]
This is a rare example where most of the bigRefs are wrongly parsed,  especially title and author are reversed

[Ogawa etal 2016_Acta_Ento.pdf](https://github.com/gsautter/goldengate-imagine/files/696631/Ogawa.etal.2016_Acta_Ento.pdf)

**Comment by gsautter** [comment]
This is due to the last name in all-caps preceding the first name or dotted initials without any separating comma ... RefParse can currently handle `Agosti D` and `AGOSTI, D.`, but not `AGOSTI D.`, the rationale being that it would be impossible to tell the last name in `AGOSTI DONAT`. This messes up author name recognition, and with it all the structure inference and subsequent parsing.

I'll try and adjust RefParse accordingly.

**Comment by gsautter** [comment]
OK, that was an easy fix, comes with the next build.
