### ISSUE TITLE
FigureCitation annotation does not work zootaxa.4377.3.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#421]
![image](https://user-images.githubusercontent.com/4609956/35723798-e3e4cd4a-07fb-11e8-8145-029c73caba05.png)

![image](https://user-images.githubusercontent.com/4609956/35723809-f44a5af6-07fb-11e8-8e0f-0517a9452fa2.png)

**Comment by gsautter** [comment]
Looks like the problem is that the dashes do not indicate ranges here, but rather act as separators between a plate number and a figure number withing the plate ... The figure citation tagging facilities just don't handle such patterns right now.
And implementation might turn out kind of hard: "3-1", "3-2", "3-3", OK (Figures 1-3 in Plate 3, respectively), but what about "3-4"? Figure 4 in Plate 3, or simply Figures 3 and 4?
This will require assessing figure citations throughout the document, determining which patterns they use, and then interpreting them accordingly. And even with that, there might well be ambiguous cases that will take human input to resolve.

**Comment by myrmoteras** [comment]
so we leave this asside until we see this a problem to solve
