### ISSUE TITLE
document structure detection malfunctioning?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#44]
@gsautter can you look at this Science paper.
![image](https://cloud.githubusercontent.com/assets/4609956/21841776/0e79ee1c-d7e4-11e6-9707-42438b0e1488.png)

the text is not detected properly, and none of the following tools works on this yellow text

[aaag2737.full.pdf](https://github.com/gsautter/goldengate-imagine/files/698354/aaag2737.full.pdf)

**Comment by myrmoteras** [comment]
@gsautter is there a simple answer to this - then I would like to have it to make the treatment online and add the link to the New York Times - or if it is more complex, then later

**Comment by gsautter** [comment]
Another real oddjob this one, of another wholly new type ... all the vertical column separators appear to be _images_, not graphics. That's why the whole fist page ends up as image label text (yellow) instead of main text (gray).

Also, the five-line-high "T" causes some structure trouble, had to remove it, but then it was fine.

I'll definitely have to investigate this one a little more, but I got it through structure detection for now so you can continue. You can download the IMF from http://plazi2.cs.umb.edu/GgServer/aaag2737.full.pdf.imf (it's too large to send by mail at 21MB, and GitHub doesn't like IMF ...)
