### ISSUE TITLE
table issue: ejt-431_boonyanusith_sanoamuang_brancelj 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#467]
![image](https://user-images.githubusercontent.com/4609956/40649653-c5062d1a-6331-11e8-8aed-4696a98015a5.png)

rows are a problem

**Comment by gsautter** [comment]
In what regard are rows a problem here? Sure, the column headers get split up in two rows, but that's even indicated graphically. Otherwise, I get all the rows individually (and so do you, judging from the text stream connectors), so what's wrong with that? Or in other words, what _should_ the rows be like?

**Comment by gsautter** [comment]
Not an issue at all ... these are just table cells spanning two columns. Show `tableCell`, and you'll see.
