### ISSUE TITLE
Scanned PDFs: Unable to find images for all pages

### ISSUE THREAD

**Issue by tdikow** [gsautter/goldengate-imagine#479]
When reading in a scanned PDF an error occurred: Unable to find images for all pages.
[Logs.zip](https://github.com/gsautter/goldengate-imagine/files/2181959/Logs.zip)
[londt_1977.pdf](https://github.com/gsautter/goldengate-imagine/files/2181961/londt_1977.pdf)

**Comment by tdikow** [comment]
Interesting to learn what the problem is. This is a scanned article I would like to add to Plazi and I have more articles from the same digitization project (Sabinet in South Africa) that might have similar issues.
Thanks for addressing this issue.

**Comment by gsautter** [comment]
Actually, a scanning project taking away all the problems of background elimination, setting the scan upright, and isolating the actual block of text is very interesting because it might well constitute a case where we can go straight for analyzing externally provided OCR (GGI is readily able to import that).

This is a best case scenario, of sorts, as OCR proper has never been GGI's strong suite, and most likely never will be - Tesseract might be good, but it's falling behind against commercial competition (ABBYY and OmniPage). Looking forward to covering this case.

**Comment by tdikow** [comment]
Did you get a chance to look into this problem further?

**Comment by gsautter** [comment]
I reduced the criteria for page scans to be accepted as such a good bit ago, so I have a working solution ... Could just be I didn't get around to creating a new build yet ... sorry, I'll try and do so in the next few days.
