### ISSUE TITLE
figure caption beginning with PLATE

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#498]
FFE8FF91FFA7407ABC1038591210FF82 

in this example, captions are not found (I marked them manually) neither the figureCitations have been linked to the captions and images.

![image](https://user-images.githubusercontent.com/4609956/46165661-7f80e400-c291-11e8-853c-96e8f0bd69df.png)

**Comment by gsautter** [comment]
Plates, I guess ... I'll simply have to add that pattern, both to the style template and to the figure citation handler.

**Comment by myrmoteras** [comment]
that would be helpful since I have seen this a couple of time

**Comment by gsautter** [comment]
What makes matters even worse is that the caption mainly consists of several sub-captions "Fig. X", and that the latter are used in the figure citations instead of the plate proper.

That's something I'll have to implement a handler for, most likely by annotating the caption as a whole as a `captionGroup` or `plateCaption`, and annotating the individual figure captions inside the group. That would have the advantage that the captions proper handle just like normal ones, i.e., ones that consist of a paragraph of their own, starting with "Fig.", etc.
On the other hand, it would do away with the one-to-one relationship of figures to captions, having multiple captions reference the same figure. And that would have some implications in the Zenodo upload and other exports ... needs some thought, this one.

**Comment by gsautter** [comment]
This one works now as well, including references to the in-line figure numbers embedded in the plate captions. And it gets the two-paragraph caption of Plate 1 as a whole.

Comes with next build, to be made after a few more tests, especially regarding false positives in the multi-paragraph caption department.
