### ISSUE TITLE
image color wrong; current biology

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#499]
The color of the images are wrong in this article: 
![image](https://user-images.githubusercontent.com/4609956/46194196-ff926280-c300-11e8-86d9-f423c2bbed9f.png)

![image](https://user-images.githubusercontent.com/4609956/46194222-16d15000-c301-11e8-9265-18a139b1eccf.png)
https://www.cell.com/current-biology/pdfExtended/S0960-9822(18)30993-X

**Comment by myrmoteras** [comment]
should I just process the file and you fix the images later, or should I better wait until you have fixed the issue?

**Comment by gsautter** [comment]
This might turn out a tricky one ... so because it's a JPEG2000 with a combination of color spaces that, judging for all previously mis-decoded figures, _requires_ inversion. Deactivating the latter brings up the image just like supposed to, but I'll need to take a very close look at that inversion switch, as otherwise we would end up mis-decoding other figures.

That said, I'd say go ahead and process this one, I'll fix the image soon as I figure out why it behaves exactly the opposite of similarly encoded images we've encountered before.

**Comment by gsautter** [comment]
Turns out there is an in-PDF inversion mechanism on top of everything else ... never seen it in this combination with color spaces, though.

Image decoding observes said inversion now, so this image comes up right ... yet another edge case covered, comes with next build.
