### ISSUE TITLE
scroling jumps over several pages

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#538]
When I scroll down a page using a mouse, it regularly jumps over several pages, and unless I control the page numbers, I unfortunately do not check the entire documment -  part of problems Terry later encounters

**Comment by gsautter** [comment]
This is actually a feature ... goes by the name of "Fast Scroll".

Background is this: to display a page, GGI has to load the page image, which can be large. So if you're headed all the way down to the bibliography, it doesn't make sense to render all the pages before, but only resume actual rendering where you stop your scroll, i.e., with the pages you were intending to look at.
However, this only kicks in if you hold the scroll bar and move up or down really fast, If you use the scroll wheel, or if you move the scroll bar at a moderate pace, all pages are rendered, and you don't miss any. 

The rendering suspension is really only for cases when you pull the scroll bar down (or up) by dozens of pages in a split second, and should not kick in otherwise. Without it, however, such quick long-distance moves would be a lot less fluent, as dozens of page images would need to be loaded and rendered in vain.

**Comment by myrmoteras** [comment]
it is a nuisance though when you check an entire document and need to see each page. you then either have to work really slowly or otherwise you can't really

**Comment by gsautter** [comment]
Guess that depends on usage behavior ... when inspecting every page, I tend to use my scroll wheel. How do you do it?

It's quite possible, though, to increase the threshold for the fast scroll mechanism, i.e., have it kick in only at a considerably higher scroll speed than now, or even make this configurable. Would that be sensible?

**Comment by myrmoteras** [comment]
I use my scroll wheel too, and this causes problems.

I just discovered: what  works is having nothing selected, or just footnote. 
If I select elements that span multiple pages, e.g. treatment, then the problem occurs and the system behaves differently. Needs more checking though

**Comment by gsautter** [comment]
Might simply be an issue of mouse speed settings, or, once again, screen resolution, as scroll speed is measured as pixels per second.

On the other hand, selecting or not selecting anything should not have an influence here, as the fast scroll switch doesn't check for that. Might simply be you're scrolling just a bit differently when holding down a mouse button for selection, or some Java side auto-scrolling causes the difference in behavior.

**Comment by gsautter** [comment]
I've made fast scroll more adaptive now, doesn't kick in as easily any more, so you won't miss any pages. Comes with next build.

**Comment by myrmoteras** [comment]
did you try it out? just select everything in a document and then scroll and compare to what is happening when nothing is selected?! The observation is, that checking a document for subSection and Treatments, subSubSection is not easy

**Comment by gsautter** [comment]
What do you mean by "select everything"? Make all the regions and annotations show in the display control? While that takes a bit of toll on rendering speed, the page image proper still takes up the lion's share.

**Comment by gsautter** [comment]
Regarding trying out, I did. What I've changed is basically the trigger happiness of the fast scroll mechanism proper, so it won't kick in as easily as used to. Meaning to say: rendering won't be suspended just so quickly any more. It takes five times faster a move now than it used to.
