### ISSUE TITLE
bibRef: author not complete jPalaeogeography.s42501-018-0014-2

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#542]
this "and" at the end of the authors makes that the last author is not tagged 

![image](https://user-images.githubusercontent.com/4609956/50044665-27cf6900-0087-11e9-9522-7261162f35eb.png)

![image](https://user-images.githubusercontent.com/4609956/50044667-374eb200-0087-11e9-8e35-c7693e699c81.png)

![image](https://user-images.githubusercontent.com/4609956/50044703-fdca7680-0087-11e9-915c-6ac9688b6da2.png)

![image](https://user-images.githubusercontent.com/4609956/50044710-1b97db80-0088-11e9-8d1a-f19d95d48973.png)

![image](https://user-images.githubusercontent.com/4609956/50044718-3407f600-0088-11e9-927b-4340a276df1f.png)

![image](https://user-images.githubusercontent.com/4609956/50044735-6285d100-0088-11e9-815a-b7c55ce6baff.png)

**Comment by gsautter** [comment]
Looks like there is a font issue with the mis-capital "o" ("LOpez", etc.).

Apart from that, I'll happily look into this one, as it's one of the rarer examples of author name part order change (first author is last name first, subsequent ones are last name last). Could be I wasn't able to test handling of such cases in sufficient depth, simply due to lack of example documents.

**Comment by gsautter** [comment]
That said, could you provide me the IMF in some kind of way? Got some 6 GB left on the Boston server, so it should still fit.

**Comment by myrmoteras** [comment]
its already on TreatmentBank. need to find it though...

**Comment by gsautter** [comment]
Done ... was quite a hard one to get working alongside the mechanisms intended to catch single-word author names alongside broken ones.
