### ISSUE TITLE
typos: what is happening down stream with corrected strings

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#555]
in this case, holotype is misspelled as holoype. And of course the parser does not detect it. What is happening downstream (e.g. GBIF, or RDF) when I annotate the typestatus properl?

![image](https://user-images.githubusercontent.com/4609956/51030674-74c93100-159a-11e9-864b-071d0b0a7ec4.png)

**Comment by gsautter** [comment]
The one place it has to be correct for most applications is the attribute of the `materialsCitation` annotation. This is where the very most consumers take it from, because this is where the normalized values (lower case, singular, etc.) usually go.
Using such a normalized value saves a great deal of hassle downstream, simply as all the cases to consider have only one value each that will trigger them. That's why we've been doing it like this pretty much from the start.
