### ISSUE TITLE
the entire article has only paragraphs

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#566]
this entire book chapter has only paragraphs

![image](https://user-images.githubusercontent.com/4609956/52017317-4c708a80-24e7-11e9-8c24-cb062ac5b15c.png)

but otherwise it processes ok. It has not treatments though. here it is 4F07FF8FFFC3271BFF5BFFF4FFA9B22E

**Comment by gsautter** [comment]
Actually, the source of the error are not the paragraphs proper, but rather the blocks ... line distance is so large in this document that every line ends up in its own block.
Dragging a box around the actual blocks and using "Merge Blocks" gets it all in order.

**Comment by gsautter** [comment]
I guess I'll have to re-visit page structure detection at some point (rather soon) to be more adaptive to document averages rather than rely upon fixed defaults in the absence of a template. I'm thinking of some accumulation point based analysis, akin to what we already have in pretty successful use in inside-block paragraph detection.
