### ISSUE TITLE
GGI BatchProcessing: Zootaxa not processed

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#582]
these files did today not process in batch

java -jar -Xmx10240m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\temp" CACHE=./BatchCache FM=U

https://drive.google.com/open?id=1XivyRD8pXwJzN1CbtIrr63oN0LcULjtr

**Comment by gsautter** [comment]
Got an error log for me? Would make testing a lot easier to know where exactly the batch failed for each one of these PDFs.

**Comment by gsautter** [comment]
OK, looks like #581 at least provides the log for `zootaxa.4555.4.6.pdf` ... I'll work from there.

**Comment by myrmoteras** [comment]
[GgImagineBatch.20190218-1335.out.zip](https://github.com/gsautter/goldengate-imagine/files/2877120/GgImagineBatch.20190218-1335.out.zip)

**Comment by gsautter** [comment]
Here my initial summary:
- `zootaxa.4555.4.1.pdf` reproduced the MC hangup, investigating (see also #580)
- `zootaxa.4555.4.1.pdf` reproduced an FAT error, investigating
- `zootaxa.4555.4.6.pdf` processed fine, see #581 
- `zootaxa.4555.4.12.pdf` required a little fix in metadata extraction (the title comes back empty because in this erratum the template doesn't match, and the extractor didn't handle that situation properly)
- `zootaxa.4557.1.1.pdf` reproduced the MC hangup, investigating

**Comment by gsautter** [comment]
Fixed FAT error in `zootaxa.4555.4.1.pdf` ... stupid thing in status update, not even an algorithmic error.

**Comment by gsautter** [comment]
Finally got `zootaxa.4555.4.1.pdf` and `zootaxa.4557.1.1.pdf` to run after another runaway fix in what mainly does MC proper name disambiguation ... some 25 collecting dates in a row did just offer all too many alternatives of piecing together the (partial) enumerations to run efficiently. Runs nice and fast now, however, after adding some filtering.

Also, I added recognition for in-line (single-paragraph) collection code lists in "Materials and Methods". And I had to add some more morphology based logic to recover collection codes omitted in "Materials and Methods" lists but still occurring in MCs ... seems to be the norm for those lists to be somewhat incomplete rather than the exception, sadly ...

Finally, I added some collecting country filtering logic that preserves collecting region "New South Wales" over collecting country "Wales" (which is an ISO country) even if "Australia" is not explicitly present in that MC paragraph. Said logic also takes care of (at least most instances of) "Island" mis-recognized as the German name of "Iceland".

**Comment by gsautter** [comment]
On top of this, I've found a few more firsts:
- Coordinates written as "16.06.31S, 145.26.27E" with dots between degrees, minutes, and seconds - this is a good bit of a problem especially in the absence of seconds because there is no way of telling apart a decimal coordinate (numbers after dot are fraction of 100) from a degree+minute one (numbers after dot are fraction of 60)
- Coordinates written with ranges as "16.03–05S, 145.29E" with an embedded dash

What to do about such odd coordinates? I've never seen this notation before anywhere ... is that a common way of denoting coordinates?

**Comment by gsautter** [comment]
Documents are up now.
