### ISSUE TITLE
taxonomicName: subsp.nov tagged as tN ejt-508_rahayu_rodda

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#604]
![image](https://user-images.githubusercontent.com/4609956/54810441-6e37f380-4c86-11e9-80c9-5d571c1adffb.png)

**Comment by gsautter** [comment]
I was trying to get this IMF from the server to take a closer look, but no luck thus far. Did you upload it already?

**Comment by gsautter** [comment]
As to my suspicion about the underlying problem: I hardly thing this very instance id patient zero, i.e., where the error originally happened, so because "nov" is not in italics. I would want to check through the document for similar errors and look at the `_step` and `_evidence` attributes of each individual instance. This would most likely point me to where things _started_ to go wrong and thus how to prevent any future instances.

**Comment by gsautter** [comment]
Fixed ... this one snuck past italics scrutiny on the botanical special rule for cultivars, which we've learned last year are rarely ever in italics even though all the other epithets of binomials are. Added a filter now.
