### ISSUE TITLE
caption in figures

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#61]
@gsautter 
is there a possibility to mark up the caption that is in a figure? If so, let me know, so I can do it.

![image](https://cloud.githubusercontent.com/assets/4609956/22619032/b1e36320-eaeb-11e6-8c4e-b84c011c812c.png)

**Comment by gsautter** [comment]
Sure ... cut the caption block off the other "text" to the left of it via "Split Block", then use "Mark Image" to mark the whole image, and afterwards use "Mark Caption" on the caption.

Hard to tell why individual sub figures come up as text anyway ... is this a scan or born-digital? In the latter case, this would be _really_ strange. Which PDF is this?

**Comment by myrmoteras** [comment]
I can send you the PDF tomorrow. It is part of a scanned ocred book that I created, using my duplex scanner and ABBYY

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by myrmoteras** [comment]
here is the link to the file. https://drive.google.com/file/d/0B_yrQwn4yBySZ00tTHQtSDFPUTQ/view?usp=sharing  the file is 50MB. I scanned the book, and OCRed it with ABBYY- Scan = 400dpi grayscale

I can't repdroduce what you say above. whenever I mark the image, the text box disappears, and I can't mark the caption.

**Comment by gsautter** [comment]
That's the intended behavior ... however, once you've marked the image, you can simply mark a block around the caption, and then the caption proper.

**Comment by myrmoteras** [comment]
@gsautter it does not work this way.
Can we skype tonight to solve this and the EJT issue? We waist too much time writing this sort of for me non-advices. 
Since these are solved problems for you, and for us a stumbling blocks for pending grant and funding applications, we better solve it?!

**Comment by gsautter** [comment]
document UUID: 585EFF93EE0C9A1BFFE0AF040F446A1E

**Comment by gsautter** [comment]
This turns out a tricky one, in more than one regard ...
First, I will have to adjust the mechanism for marking words inside `image` regions - not removing the cleanup that comes with "Mark Image", though, as that tends to be quite helpful in the general case. I rather fancy kind of a "Mark Text Block" function that (a) will do OCR and (b) will _not_ shrink any surrounding regions, at least none that are way larger than the area selected for marking the text block.
Second, I'll have to include `line` regions in the "Split Block" operation. 
Third, I'll have to revisit how marking a text block including OCR (currently only available in "Edit Page Image & Words", but better added to the main window context menu as "Mark Text Block") splits up lines and deals with descenders of one line being mingled with ascenders of the next. There is an expansion algorithm in place, but words still tend to be expanded over multiple lines in really badly mingled cases. I don't even exclude adding a dialog that will allow you to manually adjust line splits at this point, likely in a second function labeled "Mark Text Block ...".

**Comment by gsautter** [comment]
Thinking about it ... this whole thing looks like a textbook example of an assignment for a lengthy train ride, as it might well turn out a protracted affair, so I might well end up scheduling it for Friday afternoon.

**Comment by myrmoteras** [comment]
thinking about his: This is a case that is more widespread in other print media where captions are often  somewhere in the images, such PR or newspaper articles. Thus it might make sense to find a solution, not just for this particular case.

What do you suggest in terms of markup? Just mark the images up as a whole for now, and then fix it later so that I can make use of the treatments by Friday? Would that allow to mark the captions later?

**Comment by gsautter** [comment]
With the latest build, you mark the caption, and then mark the image as a whole. I have changed the bahavior of "Mark Image" in such a way that the caption will remain unscathed now.
