### ISSUE TITLE
font issue "E

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#611]
In this zootaxa.4504.1.5 the " and E are one token that cannot be separted and causes, that geocoordinates are not parsed

![image](https://user-images.githubusercontent.com/4609956/54998802-47075c00-4fcf-11e9-9b17-6a72f5a650c8.png)

**Comment by gsautter** [comment]
Have you tried "Split Word"? That function might help in such situations, in fact it is intended for this purpose.

**Comment by gsautter** [comment]
Thinking tokenization, I tend to think this "seconds of arch" is encoded as two high commas rather than a single double quote, so because only the former stick to letters, and most often correctly so (in names like "O'Neil", or in south east Asian location names, for instance).

Is the IMF on the server?
