### ISSUE TITLE
table miscodet PeerJ 6457

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#612]
https://peerj.com/articles/6457.pdf

FFF9A133FFDCFFD1D63BFFBBFF9B2969

![image](https://user-images.githubusercontent.com/4609956/55005952-38c03c80-4fdd-11e9-8450-bdc147d8323a.png)

**Comment by gsautter** [comment]
The fact that the content is flipped to the horizontal is fine ... it's just that this vertical page edge not should have been removed but failed to do so during decoding, and that consequentially the flipped block ended up being moved too far to the right.

This is a nice example, I'll see what I can do to get this right.

**Comment by gsautter** [comment]
Done, this one was a bit of a conundrum ... problem turns out to be that little progress bar next to the page numbers: it is page decoration (and should be treated as such), but the PDF fails to detect that because (a) the graphics object is different in every page and (b) doesn't even have a fixed position on the page, but moves left as the number of digits in the page number increases, foiling detection via page frequency analysis.
