### ISSUE TITLE
materialsCitation not discovered

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#613]
in this case, the materials citation has not been discovered.

http://treatment.plazi.org/id/8D5D87F2-FF83-FFE1-FF4E-2A81FEFC080B
--
![image](https://user-images.githubusercontent.com/4609956/55087866-0bda5b00-50ab-11e9-8397-1160a530ae98.png)

is there anything that could be done? having the holotype and type locality in two places is somthing that occurs recularly

**Comment by gsautter** [comment]
My initial suspicion here is that the holotype is marked initially, but later filtered, either (a) for lack of and locality or collection information (no countries, regions, locations, coordinates, collection codes or specimen codes, and no back reference, either), or for too low a fraction of proper names (too many lower case words).
"Extract Materials Citations" on the paragraph should fix that, as running that function only on a small part of a document assumes targeted use and thus ignores the aforementioned filters.

**Comment by gsautter** [comment]
The "Type locality" is another problem altogether: Right now, the Materials Citation Handler extracts materials citations from a single continuous snippet of text, plus potential backward references to preceding materials citations.
Specifying all the locality information in a separate paragraph (that does not constitute a materials citation by itself) and then referencing it from all subsequent materials citation is somewhat against the above modelling. Catching these cases will definitely require some considerable implementation for initial detection, and then a good bit of tweaking of the filters intended to prevent false positives at the paragraph level.

In particular: (a) The type locality paragraph proper needs detecting despite the absence of any specimen counts, collection codes, and specimen codes. Parsing has to work on free text locality information alone, which can end up being quite fuzzy, and subsequent filtering has to accept such a paragraph that contains nothing but locality information (usually more likely "distribution"). (b) References to the type locality further downstream have to be treated like the existing backward references. (c) We need an annotation type for the type locality in the first place as `materialsCitation` is somewhat beside the point, and outright confusing in downstream processing because it would add an extra materials citation to any statistics.

**Comment by gsautter** [comment]
To be handled in https://github.com/plazi/Plazi-Communications/issues/833
