### ISSUE TITLE
n. sp. missing

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#614]
I have a feeling that we miss to label on the todays new species  at the very moment quiet a few new species, such as this one.

http://tb.plazi.org/GgServer/html/AF03878EFFF9FF93C193F8EC7429CEB2
http://tb.plazi.org/GgServer/html/03F721294C12D50CFF32F8A719D661AF

![image](https://user-images.githubusercontent.com/4609956/55088333-dda94b00-50ab-11e9-955a-1d28be53cedf.png)

**Comment by gsautter** [comment]
Looks like we have another case of mistaken rank here, as the XML indicates rank "genus" for Bidderia bicolora ... most likely the very same problem as https://github.com/plazi/Plazi-Communications/issues/809 , will treat it as a duplicate here for the time being.

**Comment by gsautter** [comment]
See gsautter/goldengate-imagine#615 ... only very few names were ever affected, (a) because it was only one rule out of over a dozen that incurred the error and (b) because even that happened only under specific circumstances.

Anyway, fixed it now, comes with next update.

Planning scripted server side repair now.
