### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#616]
Why is CPU usage different 

importing page words

![image](https://user-images.githubusercontent.com/4609956/55161019-e3af3280-5164-11e9-8fbf-eb41103cb1b2.png)

and then maxed out?

![image](https://user-images.githubusercontent.com/4609956/55161107-0b9e9600-5165-11e9-96f0-8a26089329e3.png)

**Comment by gsautter** [comment]
Plain and simple: because PDF decoding works as much in parallel as possible (to make good use of your 8 core machine).

Computationally intensive analyses are mostly implemented to run in parallel to speed up matters. 

However, some other steps that shove data into the document (which really is more of a purpose built in-memory database) have to run sequentially because they modify multiple data structures, and synchronizing access to the latter in a parallel scenario would hardly be faster than sequential execution.

That said, PDF decoding alternates between parallel processing (which has all your cores coming to bear, and thus getting load) and sequential processing (which only uses a single core). Hence the differences in CPU load throughout the decoding process.
