### ISSUE TITLE
materialsCitation not complete: p27_42_Frey_etal

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#624]
here a MC that is missing the specimen, but otherwise looks good.

![image](https://user-images.githubusercontent.com/4609956/55719263-1deac080-59fe-11e9-89d2-d14da55ad217.png)

I will upload this, once Marcus uploaded the files to Zenodo

**Comment by gsautter** [comment]
Could you please let me know when the IMF is on the server? Kind of hard to test this without that ...

**Comment by gsautter** [comment]
On a technical level, this looks like a mere pattern problem ... in particular, we're currently only tagging the symbols (male, female, etc.) as specimen counts, but not the verbatim words "male", "female", "worker", etc. 
I think we removed the latter at some point because it used to also tag the respective words in diagnoses, descriptions, discussions, etc. ... anyway, I think the new tagger will have to insist on the presence of a digit preceding the verbatim sex or caste.

**Comment by gsautter** [comment]
To be resolved together with https://github.com/gsautter/goldengate-imagine/issues/640

**Comment by gsautter** [comment]
I just checked the gizmo that marks the specimen counts, and the ones missed here should definitely come up ... hard to verify without the document however, as I cannot seem to find it on the server.
