### ISSUE TITLE
materialsCitation: wrong MC boundaries  zootaxa.4584.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#627]
![image](https://user-images.githubusercontent.com/4609956/55854221-4ee50580-5b64-11e9-91a6-8fde9f066a93.png)

![image](https://user-images.githubusercontent.com/4609956/55855234-3de9c380-5b67-11e9-813a-3dad9e8db003.png)

![image](https://user-images.githubusercontent.com/4609956/55855553-1e9f6600-5b68-11e9-9549-97e4c52de2f4.png)

![image](https://user-images.githubusercontent.com/4609956/55856207-e4cf5f00-5b69-11e9-941d-f56504cb98cf.png)

![image](https://user-images.githubusercontent.com/4609956/55856259-0defef80-5b6a-11e9-9f3b-21cf86c0665b.png)

![image](https://user-images.githubusercontent.com/4609956/55856392-74750d80-5b6a-11e9-8657-6643f6563c48.png)

**Comment by gsautter** [comment]
"Possible syntype" is a first ...

**Comment by gsautter** [comment]
Also, not sure if "Type material:" should be included ... it's more of an in-line heading.

**Comment by gsautter** [comment]
The other problems I'll look into ... have a UUID for me?

**Comment by myrmoteras** [comment]
ok - I am uploading this file right now, so you can have a look at it. it needs some corrections regarding he MC, especially type materials.

**Comment by myrmoteras** [comment]
I can't finish the upload, because I am getting this
![image](https://user-images.githubusercontent.com/4609956/55858906-21528900-5b71-11e9-8a82-584287d1e713.png)

What to do?

**Comment by gsautter** [comment]
Regarding the heap space, start over, and maybe check your "Parameters.cnfg" for the `MAX_MEMORY` setting (might have been reverted by an update).

**Comment by gsautter** [comment]
One main problem with the "Tephritis dilacerata dilacerata (Loew 1846)" materials is that there are some spurious paragraph breaks, namely before "Kazakhstan:" and before "Russia:", which throws the extraction process off track. Removing those two paragraph breaks already improves the result a good bit.

**Comment by gsautter** [comment]
Another problem is the inlining of the "Non-type material:" heading, which basically ends the scope of "Paratypes" and established type status "other".
I'm adding such "other" type status headings now to help with the segmentation of paragraph into smaller chunks. Said chunking works based upon countries, regions, or type statuses, depending on the order they occur in, and creates smaller stretches of text to extract the remaining details from.

**Comment by gsautter** [comment]
Another problem is the inlining of the "Non-type material:" heading, which basically ends the scope of "Paratypes" and established type status "other".

I'm adding such "other" type status headings now to help with the segmentation of paragraph into smaller chunks. Said chunking works based upon countries, regions, or type statuses, depending on the order they occur in, and creates smaller stretches of text to extract the remaining details from.

**Comment by gsautter** [comment]
The reason the "Lectotype" goes missing is yet a different one: The MC marks just fine, but gets filtered downstream because it holds no information at all regarding either collecting locality or the collection the specimen is stored in. All there is are type status, specimen count (the female symbol), and brief label quote, which is preciously little to go on.
Would you be able to locate the specimen based upon that information alone, in particular without getting back to reference "Merz 1991"? If not, this is just too little.

**Comment by gsautter** [comment]
About the same applies to the "Neotype" of "Tephritis postica (Loew 1844)" ... just nothing to really work with.

**Comment by gsautter** [comment]
A general problem in this article is the unequal starts and ending of MCs:
- At the start there is locality information (countries and regions are fine, but location names are nothing to really go at because they are just generic proper names).
- At the end there is either a collection code in parentheses (most frequent, and what thus works), or a collector name in parentheses (before collection code if latter present), or a specimen count (before collector name and/or collection code if any of the latter two present), and that followed by a semicolon.

This variability at both ends of MCs make boundary detection quite challenging, even for a pair of human eyeballs ...  tough one this.

**Comment by gsautter** [comment]
There were a few issues with spurious paragraph breaks in this one, especially in the first screenshot. After ironing those out, it works fairly well now, using a scoring based technique to determine the best splitting approach (out of several options) to get rid of further duplicates.
This process is iterative, not recursive, to prevent runaways, and it stops once reaching a threshold score that indicates "no more viable splitting options available".
