### ISSUE TITLE
file do not process; zootaxa

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#652]
[GgImagineBatch.20190425-2240.out.zip](https://github.com/gsautter/goldengate-imagine/files/3118829/GgImagineBatch.20190425-2240.out.zip)

https://drive.google.com/open?id=1hHXKiL56USaPFxGTEXUxUAT3TmQuKAPX

**Comment by gsautter** [comment]
Got it ... the actual error happened in FAT, but the underlying problem was a paragraph issue (only half of a caption marked as such) incurring a `taxonomicName` marked across two text streams, or the attempt to do so, and that is not intended in IMF.

Anyway, I hardened FAT against this kind of problem and ran the batch in full to verify. Document is uploaded, UUID is `A41DA326F86CFFAEF462484CFF98574B`
