### ISSUE TITLE
figureCitation link to caption

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#656]
@gsautter could you explain me how to link such fig to the respective caption an image

![image](https://user-images.githubusercontent.com/4609956/56848609-5be75000-68eb-11e9-9b64-a5513908a56a.png)

or do it?

FFE5FF9CFFCBD87BAF7E75323B0CFFFC

otherwise it is done on on TB. BLR, GBIF, just the link to the image is missing

**Comment by gsautter** [comment]
Done ... this was a subtle one, and admittedly hard to find: in both "fig. 1" and "fig. 2" in the text, the "fi" came as a ligature, so no match on a lookup against "Fig", which is why the context menu didn't offer the "Mark Figure Citation" option. After editing the OCR text, it worked just fine.

**Comment by gsautter** [comment]
On a secondary note, please make sure to mark a plate caption as one caption, and a plate as a single image. Otherwise, the one-to-one relationship between captions and figures breaks. Couldn't do this here any more, though, because the figures were already on Zenodo, so we now have a bunch of nested captions in this one.
