### ISSUE TITLE
text coloration

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#657]
why do I get this text all in yellow, and how can I change it into the usual color scheme

![image](https://user-images.githubusercontent.com/4609956/56859028-1b3c1500-6985-11e9-99a7-7e41b4295f07.png)

**Comment by gsautter** [comment]
You can always splice the text streams back together, and set the text stream type (have to tick off the checkbox left of `word` at the top of Display Control for the options to show).

How all these paragraphs ended up in-figure labels or footnotes is hard to tell. Most likely it starts with the article title that comes on top of an image, which results in the overlaid text being (correctly) classified as in-illustration labels. Why it wasn't cut after that to continue as main text is hard to tell.

Anyway, for correcting this I'd cut the text stream before "Lee" (in "Lee en Espanol aqui") and them set the text stream type to "mainText" ... that should fix it all because the rest seems pretty much connected.
