### ISSUE TITLE
batch_ materialsCitation hanging

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#661]
[GgImagineBatch.20190503-0743.out.zip](https://github.com/gsautter/goldengate-imagine/files/3140965/GgImagineBatch.20190503-0743.out.zip)

the file is too big to add - if you need it I will have to upload it to GD at home

**Comment by gsautter** [comment]
Most likely no need to ... the most likely cause are stray unbalanced quotes (like in #598 , also found a few in #627 , if with less severe effects because paragraphs are somewhat shorter), be they part of missed or broken coordinates or not. 
I've spent the past two days getting a handle on unbalanced / stray quotes in general, and I'm close to finding a good solution.

**Comment by gsautter** [comment]
Since the update on 2019-05-15, the materials citation handler now uses scoring and comparison based approaches for both quotes and boundary detection, all but completely excluding such runaways.
