### ISSUE TITLE
materialsCitation markup not complete zootaxa.4609.1.4

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#681]
@gsautter can you look into this. I am going to upload despite the shortcomings

![image](https://user-images.githubusercontent.com/4609956/58177616-ff3a4380-7ca4-11e9-8cbd-e28b0f05b3c6.png)

**Comment by gsautter** [comment]
Sure ... looks related to https://github.com/plazi/EJT-testbed/issues/492

**Comment by gsautter** [comment]
Again the "multiple taxon names in a single MC" filter ... I'll try and think of another way of preventing false positives (regarding whether or not whole paragraphs consist of MCs).

As a workaround, you can always open the XML view of the treatment and run Analyzer "MCH.MaterialsCitationHandler" there. This works because on a partial document these filters are disabled.

**Comment by gsautter** [comment]
Repaired for now.
