### ISSUE TITLE
files do not process

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#682]
java -jar -Xmx10240m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\temp67" DT=D CACHE=./BatchCache FM=U CS=S

I used this with these files that die not process:
[GgImagineBatch.20190527-0716.out.zip](https://github.com/gsautter/goldengate-imagine/files/3222052/GgImagineBatch.20190527-0716.out.zip)

https://drive.google.com/open?id=1btVb-f4fx6K8f4aUDBucMAoUQL6r_241

there seems generally to be a problem with  extracting regions. I also will start measuring processing time, which seems to be well above what we had when we run the first large batch of Zootaxa.

**Comment by gsautter** [comment]
Done ... i.e., reproduced, fixed, and uploaded the document, UUID is `A4567E11FF89FF8CFFECFFF1BF0E2C3C`

**Comment by myrmoteras** [comment]
these are TWO files.

**Comment by gsautter** [comment]
Sorry, missed that ... did the second now as well, UUID is `FFC1E31DFFB5FF88FF844F32FFAABD4E`.

This one was a bit tricky around the figures because the captions all start with `Fig` instead of the Zootaxa usual all-caps `FIGURE`, so I had to mark the captions manually. Also, in all the bottom-up figures the caption text is embedded _in_ the bitmap, no chance of marking that (unless we OCR these bitmaps ...).
