### ISSUE TITLE
figure including text blocks and captions zootaxa.4630.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#694]
in this 600pp+ articles, quiet a series of images have been marked too widely. Is there anything that can be done to correct this automatically? to prevent in the future?

![image](https://user-images.githubusercontent.com/4609956/61128867-5c878f80-a4b3-11e9-91df-02f64dd1f10b.png)

**Comment by gsautter** [comment]
For what it looks like, the figures are just closer to the text than usual ... meaning that the difference is below the template specified minimum block distance, and maybe also below the default one (the one used in absence of a template).
Not sure what we can do in this particular case (apart from manual chopping - I just hope it doesn't affect all the figures), but we can surely adjust the template if we encounter more such cases.

**Comment by gsautter** [comment]
If we have a backlog of such cases already, it would also be possible to devise kind of a "Crop Images" function (most likely in "Edit" menu) to statistically detect such narrow margins and then apply them document-wide.

**Comment by gsautter** [comment]
OK, this is a repeating phenomenon then, I take it, now that we also have #701 ... As stated above, it is quite possible to devise a statistics driven approach for resolving this, most likely to be part of structure detection and to run right before caption markup.
Just didn't want to kick into action here for a single document. Now that there is two (and more to expect due to the quick succession they appeared in), it's a different story.

**Comment by myrmoteras** [comment]
here another image too large in todays Zootaxa.4638.2.4

![image](https://user-images.githubusercontent.com/4609956/61278002-9efee400-a7b3-11e9-8210-d564c3326a47.png)

**Comment by gsautter** [comment]
Repaired `zootaxa.4638.2.4` as well, furnishing proof that the splitting works as supposed to ... will now put out an update and then do that behemoth `zootaxa.4630.1.1` server side.

**Comment by gsautter** [comment]
`zootaxa.4630.1.1` done via single-gizmo server batch.
