### ISSUE TITLE
bibRef tagger does not work Lancet PIIS0140673618312248

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#727]
in this example, the bibRef tagger does not work.Initially, the structure of the bibRef has been wrongly tagged with number separated from the main text of the bibRef, and many bibRefs not in one paragraph
Also, when I tag the bibRef, then I can't run the parser
it is uploaded as PIIS0140673618312248

P.S. : Also all the graphics included the caption
P-P.S. the table are also special, including originally the table notes and the caption
P.P.S is also does not upload to

**Comment by myrmoteras** [comment]
now it is there 8116B650FFF0FF956263FFA84608F91A

**Comment by gsautter** [comment]
I see you did some manual reference tagging ... however, `bbiRef` won't cut it, I'm afraid. Anyway, investigating why bibliography detection goes so utterly wrong.

**Comment by gsautter** [comment]
Got it ... the problem here is that the reference numbers come without _any_ punctuation. Usually, they are either followed by a period, or enclosed in square or round brackets, but here we have none of these, just plain numbers. I'll try and adjust the numbering pattern accordingly and see whether or not that solves it.

**Comment by gsautter** [comment]
Making the terminal period on the reference numbers optional appears to have fixed it, and I marked all the citations as well ... let's see how long it takes for waiving that period to backfire ... I see keys coming up as the bibliography.
