### ISSUE TITLE
each line a paragraph b147.6

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#750]
this is an issues that regularly, not very often, shows up in document with two columns

![image](https://user-images.githubusercontent.com/4609956/64059889-01c20880-cbc5-11e9-9cfe-763e2b7cc4c6.png)

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/64059914-87de4f00-cbc5-11e9-8708-bfeb5ccf732d.png)

**Comment by gsautter** [comment]
Could be that due to the page title and/or the caption there is only one column region marked, and all the lines in the left text column are short of the right edge of said column, so they are mistaken for short-line paragraph ends ... might be I have to adjust the logic determining the parent column on paragraph and block structuring ...

**Comment by gsautter** [comment]
Confirmed ... the problem is in how block structuring emulates the parent column if none is marked. Need to modify that logic.

**Comment by gsautter** [comment]
Fixed, comes with next update.
