### ISSUE TITLE
GG Frankfurt upload: down?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#771]
@gsautter it seems that uploaded documents do not process in Frankfurt?!

**Comment by gsautter** [comment]
The server is up and running only has a bit to do right now, as it is importing all the GBIF dataset IDs at the moment. Writing them back to the documents naturally causes a ton of updates, so the new documents are most likely somewhere in line and will go to TB, GBIF, and Zenodo at some point.

I started that process yesterday evening in the hope it would be through by this morning, but as it turns out, it takes a bit longer than that. However, the server is running steadily and working off the queues. Sorry for the delay.

**Comment by gsautter** [comment]
Are there any special documents you need me to fast-track for tomorrow?

**Comment by myrmoteras** [comment]
Is there a chance to have some monitoring dashboard(console to see how busy the server is? This would reduce such requests; similarly a note that a large action is planned/on its way would be helpful..

**Comment by myrmoteras** [comment]
non urgent - just use the upload to check whether the import went through and is ok, the same to gbif. One of my QC tools

**Comment by gsautter** [comment]
We don't have such a dashboard at the moment, but it's quite possible to create one based on the same console functions I use for monitoring such updates. Such a board could be showing the queue sizes of all the background workers in charge of document distribution, for instance.

However, given that such mass retro-updates are pretty rare events, I'm not sure if it is worth building a respective visualization ...
