### ISSUE TITLE
figure do not show up: Zootaxa

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#79]
**20170221** http://tb.plazi.org/GgServer/html/0394878DFF35E3296EB09FD8FD0AFEF3; http://tb.plazi.org/GgServer/summary/FFADFFF5FF04E31D6E279958FFDAFF96

**Comment by gsautter** [comment]
Those figures _should_ be on Zenodo now (and should have before, as all the captions did have their HTTP URIs) ... `?cacheControle=force` is your friend here ...

However, for what it looks like in the XML, the figure citations are just not marked ... maybe they failed to auto-detect due to the somewhat peculiar figure numbering scheme ... just mark them, and the links _will_ show. And if not, try `?cacheControle=force` first thing.
