### ISSUE TITLE
file conversion results in strange images MyremcNews_24.123-144.pdf

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#790]
[MyremcNews_24.123-144.pdf](https://github.com/gsautter/goldengate-imagine/files/3827547/MyremcNews_24.123-144.pdf)
@gsautter can you convert this one on your side? I am getting very strange images

![image](https://user-images.githubusercontent.com/4609956/68532882-0b818e00-0323-11ea-880f-09d6e6ed9eca.png)

**Comment by gsautter** [comment]
Reproduced ... turns out the figures are sectioned into multiple rather narrow horizontal stripes, and with an extra bit of a pitfall. While we've seen such stripe-stored images before and are well able to re-assemble the whole image from them, in this case the stripes come at wildly varying resolutions (just zoom the figure on page 10 to, say, 800%, scroll around, and see the vast variations in graining ...), which we haven't covered thus far, simply because we never had such a case before ... the only reason for representing images like this is obfuscation for the sake of copy&paste protection. I'll try and figure out a way of overcoming this artificial obstacle.

**Comment by gsautter** [comment]
Fixed, added zooming of partial images for size adjustment. I did the IMF up to (including) bibliographic citations and put it on the server, UUID is `A471825CE30EFFFAA14EFFE7FFA9FFF1`.
