### ISSUE TITLE
bibRef not parsing properly 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#796]
in this file https://drive.google.com/open?id=1_nYPMiTitPQtxS89sqCKLzVhn7uUzSuI
the bibRefs are all off when running mark bibRefs

there are 99, and if there is a fix so that I don't have to edit them all one by one, that would be helpful

**Comment by gsautter** [comment]
Reproduced, analyzed, and fixed. Turns out there was a problem in the scoring formula used to select the most likely author list styling, or more specifically, one of the catching mechanisms for bibliographies with very low average numbers of authors per reference (single author in half of the references or even more) went a bit over the top, wrongfully triggering some other (penalization) mechanism intended to counteract on "trivial" styles almost always having more matching potential author lists than more sophisticated ones. In brief, this part of RefParse is a pretty delicate matter, like fuzzy logic tends to be.
Fix comes with next build. The IMF is on the server with references parsed and citations marked, UUID is `FFC2FFF97E065D17BE048C15FFCAFFB0`.
