### ISSUE TITLE
new built; release

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#824]
@gsautter can you please release the last built of GGI today so Jeremy can use it for the training course beginning Dec 6, and we can make sure all is ok?

**Comment by gsautter** [comment]
I'll try my best ... integrating these new OCR editing facilities is a bit of an open-heart surgery, and preventing future changes from being the same is even more so ... I'll try and finish the former in time, and do the latter afterwards.

**Comment by gsautter** [comment]
As to the status of the OCR editing: editing proper works nicely and all, and so does zooming, moving between lines, etc. The only tricky thing left is writing the changes to word _boundaries_ to the underlying document in a little as possible invasive fashion, as otherwise certain sequences of edits might mess up word boundaries more than required, which is not as desirable a thing considering annotation IDs hinge on the word boundaries.

**Comment by myrmoteras** [comment]
aren't there other changes you made already in response to requests from POA? Why not release those, and then take the time for your open heart surgery?

**Comment by gsautter** [comment]
Would love to, and will change the architecture that way in aforementioned _second_ surgery ... right now, the OCR editing is part of the core display facilities (from the very early days of GGI), which renders matters a bit difficult. The second surgery will change exactly that.

**Comment by gsautter** [comment]
It's done, finally ... a new built is online, and corresponding updates as well.
