### ISSUE TITLE
FigureCitation does not resolve/have hyperlinked

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#848]
FFCCFFDFFF9B8F1FFFD2714DFFBCFFEA

in this case, the figure citations are not activated, despite that they are tagged in the IMF
![image](https://user-images.githubusercontent.com/4609956/72432985-a621a180-3798-11ea-9853-0d19bde62121.png)

**Comment by gsautter** [comment]
I think this was merely a timing issue ... since the last meeting in Geneva, we're writing back the links asynchronously, so there might be a bit of a time laps between your releasing of an IMF and the links being inserted. Anyway, now the figure citation does have a link:
![image](https://user-images.githubusercontent.com/5789714/72445113-7f239980-37b1-11ea-8133-f6fb03fb1add.png)
