### ISSUE TITLE
Nature article with troubles: FFC1FFD3FFFCFFE3737FFF9B8B2FFFB6

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#849]
@gsautter lets have a look at this Nature article:
* how to deal with captions in two columns: probably because of use successor, it now has two figure deposits in BLR (see eg Fig2: https://zenodo.org/record/3609904#.XiBEDMhKjAQ  https://zenodo.org/record/3609906#.XiBD88hKjAQ 
* token separation not right in captions (see eg https://zenodo.org/record/3609902#.XiBBe8hKjAQ

let's see how to fix this - and to deal with captions on two column

**Comment by gsautter** [comment]
Two-column captions should not really be an issue as long as the word relations are set correctly, i.e., there is no paragraph break between the columns ... I do understand that _marking_ multi-column captions is a bit cumbersome, but in general should work.
I repaired all the captions now and had the server clean up the obsolete figure depositions.

**Comment by gsautter** [comment]
The spacing issue with Figure 1 was due to the words in the first line of the caption being so densely packed (only 2 pixels apart in some cases) that the generic formula for the minimum width of a space returned "too close for a space at this font size" and thus conflated the words. Added an explicit minimum space width to the uploader now, so the caption in Figure 1 is fixed.

**Comment by myrmoteras** [comment]
tx - I obviously missed then the word relation... damn
