### ISSUE TITLE
zoobank LSID / specimenCode mess up zootaxa.4729.1.11

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#879]
Here is an issue to look into:
![image](https://user-images.githubusercontent.com/4609956/73233870-3217ce00-4188-11ea-858d-01b6f83ece8e.png)

http://tb.plazi.org/GgServer/html/03D10D23FFFD542FFF572B26FE03F82B

FFE8755BFFFD542FFFC02E0EFF95FFEE

**Comment by gsautter** [comment]
Looks like `CF804316` was accidentally recognized (or mistaken for) and tagged as a GenBank accession number because it matches the general morphology of two upper case letters followed by six digits ... a rare case of some prefix of a UUID matching that morphology (6/16^2 * 10/16^6 ~= 0.008382, to be a total nerd) ... but then, not all that unlikely to occur at some point regarding all our data ...

Anyway, looks like we should introduce a filter that (a) finds UUIDs and (b) filters out anything that might have been marked as meaningful inside them, as rare an event that might be (<1%) ...

**Comment by myrmoteras** [comment]
I am the rare case uncoverer...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gsautter** [comment]
As I already stated to @mguidoti ... the data _never_ runs out of surprises ... something I've learned all too well by now ...

**Comment by mguidoti** [comment]
Greatest data-related quote ever.

**Comment by gsautter** [comment]
Turns out we already had taggers for UUIDs, URIs, and gene sequences ... primarily used to filter collection codes ... extended those filters now to also remove accession numbers nested in one of these larger structures, comes with next update.
