### ISSUE TITLE
messed-up word flow impares DOI recognition

### ISSUE THREAD

**Issue by Carol-Sokolowicz** [gsautter/goldengate-imagine#881]
Hi Guido, I'm Carol working from the Porto Alegre office.
I've been working on a new template for Nauplius journal. We already new that it was a problematic journal since it has a lot of template-related issues, but we thought it was a good way of finding new challenges. So, this is not an urgent issue.
 I was having some problems  while working on a pattern for DOI recognition. In some PDFs files it worked and in other it didn't.
It turned out that if I fixed the word flow that was wrongly connecting the DOI number with the main text, the DOI was recognized fine. 
Is this a issue, right? Since this manual fix in the word flow will not be done in the batch process. 
Any thoughts?
Here are some screenshots of the problem.

Messed-up word flow:
![image](https://user-images.githubusercontent.com/57491712/73383267-c593f080-42a7-11ea-866d-9fe81e9e9fbe.png)

Fixed word flow
![image](https://user-images.githubusercontent.com/57491712/73383356-ed835400-42a7-11ea-809e-85380c60ffee.png)

**Comment by gsautter** [comment]
First of all, Hi @Carol-Sokolowicz

I have an idea how we might be able to tackle this issue, namely to ignore text streams and work with the topological sort order of the words. The latter is also the basis for establishing the text streams when decoding a PDF, but as you've seen, the text streams change later, and relying on their basic order along would essentially mean ignoring later text stream edits ... enough Chinese ...

However, to implement such a change, a test document would be extremely helpful ... can you share the IMF with me you took these screenshots with? Or is it one that is already online, be it Google Drive or the Plazi server, just so I can get my hands on a test case.

**Comment by Carol-Sokolowicz** [comment]
I understood a little bit of your Chinese...
Here is the IMF, sorry I forgot.
https://drive.google.com/open?id=151kAReZBBZ1KK2QhBbLX1hD1jCnRdMLH

**Comment by gsautter** [comment]
Thanks for the IMF. After testing little bit, I concluded that there is a better way than extracting metadata attributes across text stream boundaries: 
Since the DOI doesn't belong to the main text anyway (and neither does any of the other stuff on the left of the first page), we need to make sure to cut it out anyway, and a handy way of doing this is to use "General Page Layout > Page Layout > Layout of First Page" and specify the whole left side decoration as a header area (solely for the first page, of course). This will prompt document structure detection to turn that whole left side into a page header, and with that also into one coherent text stream, which then includes the entire DOI. After that, metadata extraction again works as used to.

**Comment by Carol-Sokolowicz** [comment]
Interesting!
Let you now later on if it worked when I get back to this template.
Thanks

**Comment by Carol-Sokolowicz** [comment]
Hi @gsautter , just to close this issue. As you've helped me in the POA office, after we marked all the left region of the first page as a header, the DOI marking worked fine! Thanks

**Comment by gsautter** [comment]
Glad it's working now, always happy to help.
