### ISSUE TITLE
how to link figure citation without Fig. Abb,,. etc.

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#96]
In this paper, there is a figure in a plate at the end . How can I link it?

http://tb.plazi.org/GgServer/html/03DAE12EFFFCFF9EFE689365F8EFF5D3 

![image](https://cloud.githubusercontent.com/assets/4609956/23332145/27db8226-fb75-11e6-98f0-64f38e3d167c.png)

https://zenodo.org/record/322505#.WLGhM5orLAQ

**Comment by gsautter** [comment]
Hard one ... especially since the figure / plate is dubbed a table here, and there is no numbering. On top being in 200 year old French ... afraid the automated tools won't do the trick here, there's just too litle to go at.

You could fully manually create the `figureCitation` annotation and then set the attributes. Just look at any other document to see which attributes to add.

**Comment by myrmoteras** [comment]
it is not just "look at". May be something to consider to expand the automated routine we have.

here is the manual how to actually do it.

https://docs.google.com/document/d/1mRSK4g0AVS1L4lbTYKH0Sq-7JRX5qEWfPsYGNcWJE6A/edit#heading=h.snqkzv3helyd
