### ISSUE TITLE
figure replacement in GGI

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#99]
@gsautter does it matter, whether their is a one pixel difference in the box between the original image that need be replaced, and the new corrected image extracted using the source.pdf?

![Uploading image.png…]()

![Uploading image.png…]()

**Comment by gsautter** [comment]
No ... what matters is (a) the `targetBox` attribute of the `caption` annotation (usually generated from the `figure` region marked in the page), and (b) that the bounding box of the figure supplement (the original PNG image as extracted from the PDF) maximally overlaps with that `targetBox` - an exact match is not required there.

**Comment by gsautter** [comment]
The rationale is that (a) figure images might well come with graphics representing anything from a frame to a white line passe-par-tout and (b) the in-page `image` region might well be truncated due to the figure image having white margins on whichever edge. Bottom line: This matchup is reasonably fuzzy, enough to cover all the usual cases.
